/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.AutoTestStepApiResult;
import ru.testit.adaptersapi.model.LabelApiResult;
import ru.testit.adaptersapi.model.LinkApiResult;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * AutoTestApiResult
 */
@JsonPropertyOrder({
  AutoTestApiResult.JSON_PROPERTY_ID,
  AutoTestApiResult.JSON_PROPERTY_PROJECT_ID,
  AutoTestApiResult.JSON_PROPERTY_NAME,
  AutoTestApiResult.JSON_PROPERTY_IS_FLAKY,
  AutoTestApiResult.JSON_PROPERTY_GLOBAL_ID,
  AutoTestApiResult.JSON_PROPERTY_EXTERNAL_ID,
  AutoTestApiResult.JSON_PROPERTY_NAMESPACE,
  AutoTestApiResult.JSON_PROPERTY_CLASSNAME,
  AutoTestApiResult.JSON_PROPERTY_STEPS,
  AutoTestApiResult.JSON_PROPERTY_SETUP,
  AutoTestApiResult.JSON_PROPERTY_TEARDOWN,
  AutoTestApiResult.JSON_PROPERTY_TITLE,
  AutoTestApiResult.JSON_PROPERTY_DESCRIPTION,
  AutoTestApiResult.JSON_PROPERTY_EXTERNAL_KEY,
  AutoTestApiResult.JSON_PROPERTY_LINKS,
  AutoTestApiResult.JSON_PROPERTY_LABELS,
  AutoTestApiResult.JSON_PROPERTY_TAGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class AutoTestApiResult {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @jakarta.annotation.Nonnull
  private UUID projectId;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_IS_FLAKY = "isFlaky";
  @jakarta.annotation.Nonnull
  private Boolean isFlaky;

  public static final String JSON_PROPERTY_GLOBAL_ID = "globalId";
  @jakarta.annotation.Nonnull
  private Long globalId;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private JsonNullable<String> externalId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  private JsonNullable<String> namespace = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CLASSNAME = "classname";
  private JsonNullable<String> classname = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STEPS = "steps";
  private JsonNullable<List<AutoTestStepApiResult>> steps = JsonNullable.<List<AutoTestStepApiResult>>undefined();

  public static final String JSON_PROPERTY_SETUP = "setup";
  private JsonNullable<List<AutoTestStepApiResult>> setup = JsonNullable.<List<AutoTestStepApiResult>>undefined();

  public static final String JSON_PROPERTY_TEARDOWN = "teardown";
  private JsonNullable<List<AutoTestStepApiResult>> teardown = JsonNullable.<List<AutoTestStepApiResult>>undefined();

  public static final String JSON_PROPERTY_TITLE = "title";
  private JsonNullable<String> title = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXTERNAL_KEY = "externalKey";
  private JsonNullable<String> externalKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LINKS = "links";
  private JsonNullable<List<LinkApiResult>> links = JsonNullable.<List<LinkApiResult>>undefined();

  public static final String JSON_PROPERTY_LABELS = "labels";
  private JsonNullable<List<LabelApiResult>> labels = JsonNullable.<List<LabelApiResult>>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<List<String>> tags = JsonNullable.<List<String>>undefined();

  public AutoTestApiResult() { 
  }

  public AutoTestApiResult id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public AutoTestApiResult projectId(@jakarta.annotation.Nonnull UUID projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@jakarta.annotation.Nonnull UUID projectId) {
    this.projectId = projectId;
  }


  public AutoTestApiResult name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public AutoTestApiResult isFlaky(@jakarta.annotation.Nonnull Boolean isFlaky) {
    this.isFlaky = isFlaky;
    return this;
  }

  /**
   * Get isFlaky
   * @return isFlaky
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_FLAKY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsFlaky() {
    return isFlaky;
  }


  @JsonProperty(JSON_PROPERTY_IS_FLAKY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsFlaky(@jakarta.annotation.Nonnull Boolean isFlaky) {
    this.isFlaky = isFlaky;
  }


  public AutoTestApiResult globalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
    return this;
  }

  /**
   * Get globalId
   * @return globalId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getGlobalId() {
    return globalId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGlobalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
  }


  public AutoTestApiResult externalId(@jakarta.annotation.Nullable String externalId) {
    this.externalId = JsonNullable.<String>of(externalId);
    return this;
  }

  /**
   * Get externalId
   * @return externalId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getExternalId() {
        return externalId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExternalId_JsonNullable() {
    return externalId;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  public void setExternalId_JsonNullable(JsonNullable<String> externalId) {
    this.externalId = externalId;
  }

  public void setExternalId(@jakarta.annotation.Nullable String externalId) {
    this.externalId = JsonNullable.<String>of(externalId);
  }


  public AutoTestApiResult namespace(@jakarta.annotation.Nullable String namespace) {
    this.namespace = JsonNullable.<String>of(namespace);
    return this;
  }

  /**
   * Get namespace
   * @return namespace
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getNamespace() {
        return namespace.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNamespace_JsonNullable() {
    return namespace;
  }
  
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  public void setNamespace_JsonNullable(JsonNullable<String> namespace) {
    this.namespace = namespace;
  }

  public void setNamespace(@jakarta.annotation.Nullable String namespace) {
    this.namespace = JsonNullable.<String>of(namespace);
  }


  public AutoTestApiResult classname(@jakarta.annotation.Nullable String classname) {
    this.classname = JsonNullable.<String>of(classname);
    return this;
  }

  /**
   * Get classname
   * @return classname
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getClassname() {
        return classname.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CLASSNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getClassname_JsonNullable() {
    return classname;
  }
  
  @JsonProperty(JSON_PROPERTY_CLASSNAME)
  public void setClassname_JsonNullable(JsonNullable<String> classname) {
    this.classname = classname;
  }

  public void setClassname(@jakarta.annotation.Nullable String classname) {
    this.classname = JsonNullable.<String>of(classname);
  }


  public AutoTestApiResult steps(@jakarta.annotation.Nullable List<AutoTestStepApiResult> steps) {
    this.steps = JsonNullable.<List<AutoTestStepApiResult>>of(steps);
    return this;
  }

  public AutoTestApiResult addStepsItem(AutoTestStepApiResult stepsItem) {
    if (this.steps == null || !this.steps.isPresent()) {
      this.steps = JsonNullable.<List<AutoTestStepApiResult>>of(new ArrayList<>());
    }
    try {
      this.steps.get().add(stepsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get steps
   * @return steps
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AutoTestStepApiResult> getSteps() {
        return steps.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AutoTestStepApiResult>> getSteps_JsonNullable() {
    return steps;
  }
  
  @JsonProperty(JSON_PROPERTY_STEPS)
  public void setSteps_JsonNullable(JsonNullable<List<AutoTestStepApiResult>> steps) {
    this.steps = steps;
  }

  public void setSteps(@jakarta.annotation.Nullable List<AutoTestStepApiResult> steps) {
    this.steps = JsonNullable.<List<AutoTestStepApiResult>>of(steps);
  }


  public AutoTestApiResult setup(@jakarta.annotation.Nullable List<AutoTestStepApiResult> setup) {
    this.setup = JsonNullable.<List<AutoTestStepApiResult>>of(setup);
    return this;
  }

  public AutoTestApiResult addSetupItem(AutoTestStepApiResult setupItem) {
    if (this.setup == null || !this.setup.isPresent()) {
      this.setup = JsonNullable.<List<AutoTestStepApiResult>>of(new ArrayList<>());
    }
    try {
      this.setup.get().add(setupItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get setup
   * @return setup
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AutoTestStepApiResult> getSetup() {
        return setup.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SETUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AutoTestStepApiResult>> getSetup_JsonNullable() {
    return setup;
  }
  
  @JsonProperty(JSON_PROPERTY_SETUP)
  public void setSetup_JsonNullable(JsonNullable<List<AutoTestStepApiResult>> setup) {
    this.setup = setup;
  }

  public void setSetup(@jakarta.annotation.Nullable List<AutoTestStepApiResult> setup) {
    this.setup = JsonNullable.<List<AutoTestStepApiResult>>of(setup);
  }


  public AutoTestApiResult teardown(@jakarta.annotation.Nullable List<AutoTestStepApiResult> teardown) {
    this.teardown = JsonNullable.<List<AutoTestStepApiResult>>of(teardown);
    return this;
  }

  public AutoTestApiResult addTeardownItem(AutoTestStepApiResult teardownItem) {
    if (this.teardown == null || !this.teardown.isPresent()) {
      this.teardown = JsonNullable.<List<AutoTestStepApiResult>>of(new ArrayList<>());
    }
    try {
      this.teardown.get().add(teardownItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get teardown
   * @return teardown
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AutoTestStepApiResult> getTeardown() {
        return teardown.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEARDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AutoTestStepApiResult>> getTeardown_JsonNullable() {
    return teardown;
  }
  
  @JsonProperty(JSON_PROPERTY_TEARDOWN)
  public void setTeardown_JsonNullable(JsonNullable<List<AutoTestStepApiResult>> teardown) {
    this.teardown = teardown;
  }

  public void setTeardown(@jakarta.annotation.Nullable List<AutoTestStepApiResult> teardown) {
    this.teardown = JsonNullable.<List<AutoTestStepApiResult>>of(teardown);
  }


  public AutoTestApiResult title(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTitle() {
        return title.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTitle_JsonNullable() {
    return title;
  }
  
  @JsonProperty(JSON_PROPERTY_TITLE)
  public void setTitle_JsonNullable(JsonNullable<String> title) {
    this.title = title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
  }


  public AutoTestApiResult description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public AutoTestApiResult externalKey(@jakarta.annotation.Nullable String externalKey) {
    this.externalKey = JsonNullable.<String>of(externalKey);
    return this;
  }

  /**
   * Get externalKey
   * @return externalKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getExternalKey() {
        return externalKey.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXTERNAL_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExternalKey_JsonNullable() {
    return externalKey;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTERNAL_KEY)
  public void setExternalKey_JsonNullable(JsonNullable<String> externalKey) {
    this.externalKey = externalKey;
  }

  public void setExternalKey(@jakarta.annotation.Nullable String externalKey) {
    this.externalKey = JsonNullable.<String>of(externalKey);
  }


  public AutoTestApiResult links(@jakarta.annotation.Nullable List<LinkApiResult> links) {
    this.links = JsonNullable.<List<LinkApiResult>>of(links);
    return this;
  }

  public AutoTestApiResult addLinksItem(LinkApiResult linksItem) {
    if (this.links == null || !this.links.isPresent()) {
      this.links = JsonNullable.<List<LinkApiResult>>of(new ArrayList<>());
    }
    try {
      this.links.get().add(linksItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<LinkApiResult> getLinks() {
        return links.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<LinkApiResult>> getLinks_JsonNullable() {
    return links;
  }
  
  @JsonProperty(JSON_PROPERTY_LINKS)
  public void setLinks_JsonNullable(JsonNullable<List<LinkApiResult>> links) {
    this.links = links;
  }

  public void setLinks(@jakarta.annotation.Nullable List<LinkApiResult> links) {
    this.links = JsonNullable.<List<LinkApiResult>>of(links);
  }


  public AutoTestApiResult labels(@jakarta.annotation.Nullable List<LabelApiResult> labels) {
    this.labels = JsonNullable.<List<LabelApiResult>>of(labels);
    return this;
  }

  public AutoTestApiResult addLabelsItem(LabelApiResult labelsItem) {
    if (this.labels == null || !this.labels.isPresent()) {
      this.labels = JsonNullable.<List<LabelApiResult>>of(new ArrayList<>());
    }
    try {
      this.labels.get().add(labelsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<LabelApiResult> getLabels() {
        return labels.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<LabelApiResult>> getLabels_JsonNullable() {
    return labels;
  }
  
  @JsonProperty(JSON_PROPERTY_LABELS)
  public void setLabels_JsonNullable(JsonNullable<List<LabelApiResult>> labels) {
    this.labels = labels;
  }

  public void setLabels(@jakarta.annotation.Nullable List<LabelApiResult> labels) {
    this.labels = JsonNullable.<List<LabelApiResult>>of(labels);
  }


  public AutoTestApiResult tags(@jakarta.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
    return this;
  }

  public AutoTestApiResult addTagsItem(String tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<String> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<List<String>> tags) {
    this.tags = tags;
  }

  public void setTags(@jakarta.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
  }


  /**
   * Return true if this AutoTestApiResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoTestApiResult autoTestApiResult = (AutoTestApiResult) o;
    return Objects.equals(this.id, autoTestApiResult.id) &&
        Objects.equals(this.projectId, autoTestApiResult.projectId) &&
        Objects.equals(this.name, autoTestApiResult.name) &&
        Objects.equals(this.isFlaky, autoTestApiResult.isFlaky) &&
        Objects.equals(this.globalId, autoTestApiResult.globalId) &&
        equalsNullable(this.externalId, autoTestApiResult.externalId) &&
        equalsNullable(this.namespace, autoTestApiResult.namespace) &&
        equalsNullable(this.classname, autoTestApiResult.classname) &&
        equalsNullable(this.steps, autoTestApiResult.steps) &&
        equalsNullable(this.setup, autoTestApiResult.setup) &&
        equalsNullable(this.teardown, autoTestApiResult.teardown) &&
        equalsNullable(this.title, autoTestApiResult.title) &&
        equalsNullable(this.description, autoTestApiResult.description) &&
        equalsNullable(this.externalKey, autoTestApiResult.externalKey) &&
        equalsNullable(this.links, autoTestApiResult.links) &&
        equalsNullable(this.labels, autoTestApiResult.labels) &&
        equalsNullable(this.tags, autoTestApiResult.tags);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, name, isFlaky, globalId, hashCodeNullable(externalId), hashCodeNullable(namespace), hashCodeNullable(classname), hashCodeNullable(steps), hashCodeNullable(setup), hashCodeNullable(teardown), hashCodeNullable(title), hashCodeNullable(description), hashCodeNullable(externalKey), hashCodeNullable(links), hashCodeNullable(labels), hashCodeNullable(tags));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoTestApiResult {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isFlaky: ").append(toIndentedString(isFlaky)).append("\n");
    sb.append("    globalId: ").append(toIndentedString(globalId)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    classname: ").append(toIndentedString(classname)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    setup: ").append(toIndentedString(setup)).append("\n");
    sb.append("    teardown: ").append(toIndentedString(teardown)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    externalKey: ").append(toIndentedString(externalKey)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

