/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * AutoTestFilterApiModel
 */
@JsonPropertyOrder({
  AutoTestFilterApiModel.JSON_PROPERTY_PROJECT_IDS,
  AutoTestFilterApiModel.JSON_PROPERTY_EXTERNAL_IDS,
  AutoTestFilterApiModel.JSON_PROPERTY_GLOBAL_IDS,
  AutoTestFilterApiModel.JSON_PROPERTY_NAME,
  AutoTestFilterApiModel.JSON_PROPERTY_IS_FLAKY,
  AutoTestFilterApiModel.JSON_PROPERTY_IS_DELETED,
  AutoTestFilterApiModel.JSON_PROPERTY_NAMESPACE,
  AutoTestFilterApiModel.JSON_PROPERTY_CLASS_NAME,
  AutoTestFilterApiModel.JSON_PROPERTY_EXTERNAL_KEY,
  AutoTestFilterApiModel.JSON_PROPERTY_TAGS,
  AutoTestFilterApiModel.JSON_PROPERTY_EXCLUDE_TAGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class AutoTestFilterApiModel {
  public static final String JSON_PROPERTY_PROJECT_IDS = "projectIds";
  private JsonNullable<Set<UUID>> projectIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_EXTERNAL_IDS = "externalIds";
  private JsonNullable<Set<String>> externalIds = JsonNullable.<Set<String>>undefined();

  public static final String JSON_PROPERTY_GLOBAL_IDS = "globalIds";
  private JsonNullable<Set<Long>> globalIds = JsonNullable.<Set<Long>>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_FLAKY = "isFlaky";
  private JsonNullable<Boolean> isFlaky = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  private JsonNullable<Boolean> isDeleted = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  private JsonNullable<String> namespace = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CLASS_NAME = "className";
  private JsonNullable<String> className = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXTERNAL_KEY = "externalKey";
  private JsonNullable<String> externalKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<Set<String>> tags = JsonNullable.<Set<String>>undefined();

  public static final String JSON_PROPERTY_EXCLUDE_TAGS = "excludeTags";
  private JsonNullable<Set<String>> excludeTags = JsonNullable.<Set<String>>undefined();

  public AutoTestFilterApiModel() { 
  }

  public AutoTestFilterApiModel projectIds(@jakarta.annotation.Nullable Set<UUID> projectIds) {
    this.projectIds = JsonNullable.<Set<UUID>>of(projectIds);
    return this;
  }

  public AutoTestFilterApiModel addProjectIdsItem(UUID projectIdsItem) {
    if (this.projectIds == null || !this.projectIds.isPresent()) {
      this.projectIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.projectIds.get().add(projectIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies an autotest projects IDs to search for
   * @return projectIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getProjectIds() {
        return projectIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROJECT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getProjectIds_JsonNullable() {
    return projectIds;
  }
  
  @JsonProperty(JSON_PROPERTY_PROJECT_IDS)
  public void setProjectIds_JsonNullable(JsonNullable<Set<UUID>> projectIds) {
    this.projectIds = projectIds;
  }

  public void setProjectIds(@jakarta.annotation.Nullable Set<UUID> projectIds) {
    this.projectIds = JsonNullable.<Set<UUID>>of(projectIds);
  }


  public AutoTestFilterApiModel externalIds(@jakarta.annotation.Nullable Set<String> externalIds) {
    this.externalIds = JsonNullable.<Set<String>>of(externalIds);
    return this;
  }

  public AutoTestFilterApiModel addExternalIdsItem(String externalIdsItem) {
    if (this.externalIds == null || !this.externalIds.isPresent()) {
      this.externalIds = JsonNullable.<Set<String>>of(new LinkedHashSet<>());
    }
    try {
      this.externalIds.get().add(externalIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies an autotest external IDs to search for
   * @return externalIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<String> getExternalIds() {
        return externalIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXTERNAL_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<String>> getExternalIds_JsonNullable() {
    return externalIds;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTERNAL_IDS)
  public void setExternalIds_JsonNullable(JsonNullable<Set<String>> externalIds) {
    this.externalIds = externalIds;
  }

  public void setExternalIds(@jakarta.annotation.Nullable Set<String> externalIds) {
    this.externalIds = JsonNullable.<Set<String>>of(externalIds);
  }


  public AutoTestFilterApiModel globalIds(@jakarta.annotation.Nullable Set<Long> globalIds) {
    this.globalIds = JsonNullable.<Set<Long>>of(globalIds);
    return this;
  }

  public AutoTestFilterApiModel addGlobalIdsItem(Long globalIdsItem) {
    if (this.globalIds == null || !this.globalIds.isPresent()) {
      this.globalIds = JsonNullable.<Set<Long>>of(new LinkedHashSet<>());
    }
    try {
      this.globalIds.get().add(globalIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies an autotest global IDs to search for
   * @return globalIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<Long> getGlobalIds() {
        return globalIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GLOBAL_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<Long>> getGlobalIds_JsonNullable() {
    return globalIds;
  }
  
  @JsonProperty(JSON_PROPERTY_GLOBAL_IDS)
  public void setGlobalIds_JsonNullable(JsonNullable<Set<Long>> globalIds) {
    this.globalIds = globalIds;
  }

  public void setGlobalIds(@jakarta.annotation.Nullable Set<Long> globalIds) {
    this.globalIds = JsonNullable.<Set<Long>>of(globalIds);
  }


  public AutoTestFilterApiModel name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Specifies an autotest name to search for
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public AutoTestFilterApiModel isFlaky(@jakarta.annotation.Nullable Boolean isFlaky) {
    this.isFlaky = JsonNullable.<Boolean>of(isFlaky);
    return this;
  }

  /**
   * Specifies an autotest flaky status to search for
   * @return isFlaky
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsFlaky() {
        return isFlaky.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_FLAKY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsFlaky_JsonNullable() {
    return isFlaky;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_FLAKY)
  public void setIsFlaky_JsonNullable(JsonNullable<Boolean> isFlaky) {
    this.isFlaky = isFlaky;
  }

  public void setIsFlaky(@jakarta.annotation.Nullable Boolean isFlaky) {
    this.isFlaky = JsonNullable.<Boolean>of(isFlaky);
  }


  public AutoTestFilterApiModel isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
    return this;
  }

  /**
   * Specifies an autotest deleted status to search for
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsDeleted() {
        return isDeleted.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsDeleted_JsonNullable() {
    return isDeleted;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  public void setIsDeleted_JsonNullable(JsonNullable<Boolean> isDeleted) {
    this.isDeleted = isDeleted;
  }

  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
  }


  public AutoTestFilterApiModel namespace(@jakarta.annotation.Nullable String namespace) {
    this.namespace = JsonNullable.<String>of(namespace);
    return this;
  }

  /**
   * Specifies an autotest namespace to search for
   * @return namespace
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getNamespace() {
        return namespace.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNamespace_JsonNullable() {
    return namespace;
  }
  
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  public void setNamespace_JsonNullable(JsonNullable<String> namespace) {
    this.namespace = namespace;
  }

  public void setNamespace(@jakarta.annotation.Nullable String namespace) {
    this.namespace = JsonNullable.<String>of(namespace);
  }


  public AutoTestFilterApiModel className(@jakarta.annotation.Nullable String className) {
    this.className = JsonNullable.<String>of(className);
    return this;
  }

  /**
   * Specifies an autotest class name to search for
   * @return className
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getClassName() {
        return className.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CLASS_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getClassName_JsonNullable() {
    return className;
  }
  
  @JsonProperty(JSON_PROPERTY_CLASS_NAME)
  public void setClassName_JsonNullable(JsonNullable<String> className) {
    this.className = className;
  }

  public void setClassName(@jakarta.annotation.Nullable String className) {
    this.className = JsonNullable.<String>of(className);
  }


  public AutoTestFilterApiModel externalKey(@jakarta.annotation.Nullable String externalKey) {
    this.externalKey = JsonNullable.<String>of(externalKey);
    return this;
  }

  /**
   * Specifies an autotest external key to search for
   * @return externalKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getExternalKey() {
        return externalKey.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXTERNAL_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExternalKey_JsonNullable() {
    return externalKey;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTERNAL_KEY)
  public void setExternalKey_JsonNullable(JsonNullable<String> externalKey) {
    this.externalKey = externalKey;
  }

  public void setExternalKey(@jakarta.annotation.Nullable String externalKey) {
    this.externalKey = JsonNullable.<String>of(externalKey);
  }


  public AutoTestFilterApiModel tags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = JsonNullable.<Set<String>>of(tags);
    return this;
  }

  public AutoTestFilterApiModel addTagsItem(String tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<Set<String>>of(new LinkedHashSet<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies an autotest tags to search for
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<String> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<String>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<Set<String>> tags) {
    this.tags = tags;
  }

  public void setTags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = JsonNullable.<Set<String>>of(tags);
  }


  public AutoTestFilterApiModel excludeTags(@jakarta.annotation.Nullable Set<String> excludeTags) {
    this.excludeTags = JsonNullable.<Set<String>>of(excludeTags);
    return this;
  }

  public AutoTestFilterApiModel addExcludeTagsItem(String excludeTagsItem) {
    if (this.excludeTags == null || !this.excludeTags.isPresent()) {
      this.excludeTags = JsonNullable.<Set<String>>of(new LinkedHashSet<>());
    }
    try {
      this.excludeTags.get().add(excludeTagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies an autotest tags to exclude
   * @return excludeTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<String> getExcludeTags() {
        return excludeTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXCLUDE_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<String>> getExcludeTags_JsonNullable() {
    return excludeTags;
  }
  
  @JsonProperty(JSON_PROPERTY_EXCLUDE_TAGS)
  public void setExcludeTags_JsonNullable(JsonNullable<Set<String>> excludeTags) {
    this.excludeTags = excludeTags;
  }

  public void setExcludeTags(@jakarta.annotation.Nullable Set<String> excludeTags) {
    this.excludeTags = JsonNullable.<Set<String>>of(excludeTags);
  }


  /**
   * Return true if this AutoTestFilterApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoTestFilterApiModel autoTestFilterApiModel = (AutoTestFilterApiModel) o;
    return equalsNullable(this.projectIds, autoTestFilterApiModel.projectIds) &&
        equalsNullable(this.externalIds, autoTestFilterApiModel.externalIds) &&
        equalsNullable(this.globalIds, autoTestFilterApiModel.globalIds) &&
        equalsNullable(this.name, autoTestFilterApiModel.name) &&
        equalsNullable(this.isFlaky, autoTestFilterApiModel.isFlaky) &&
        equalsNullable(this.isDeleted, autoTestFilterApiModel.isDeleted) &&
        equalsNullable(this.namespace, autoTestFilterApiModel.namespace) &&
        equalsNullable(this.className, autoTestFilterApiModel.className) &&
        equalsNullable(this.externalKey, autoTestFilterApiModel.externalKey) &&
        equalsNullable(this.tags, autoTestFilterApiModel.tags) &&
        equalsNullable(this.excludeTags, autoTestFilterApiModel.excludeTags);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(projectIds), hashCodeNullable(externalIds), hashCodeNullable(globalIds), hashCodeNullable(name), hashCodeNullable(isFlaky), hashCodeNullable(isDeleted), hashCodeNullable(namespace), hashCodeNullable(className), hashCodeNullable(externalKey), hashCodeNullable(tags), hashCodeNullable(excludeTags));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoTestFilterApiModel {\n");
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    externalIds: ").append(toIndentedString(externalIds)).append("\n");
    sb.append("    globalIds: ").append(toIndentedString(globalIds)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isFlaky: ").append(toIndentedString(isFlaky)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    externalKey: ").append(toIndentedString(externalKey)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    excludeTags: ").append(toIndentedString(excludeTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

