/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.AttachmentApiResult;
import ru.testit.adaptersapi.model.AvailableTestResultOutcome;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * AutoTestStepResult
 */
@JsonPropertyOrder({
  AutoTestStepResult.JSON_PROPERTY_TITLE,
  AutoTestStepResult.JSON_PROPERTY_DESCRIPTION,
  AutoTestStepResult.JSON_PROPERTY_INFO,
  AutoTestStepResult.JSON_PROPERTY_STARTED_ON,
  AutoTestStepResult.JSON_PROPERTY_COMPLETED_ON,
  AutoTestStepResult.JSON_PROPERTY_DURATION,
  AutoTestStepResult.JSON_PROPERTY_OUTCOME,
  AutoTestStepResult.JSON_PROPERTY_STEP_RESULTS,
  AutoTestStepResult.JSON_PROPERTY_ATTACHMENTS,
  AutoTestStepResult.JSON_PROPERTY_PARAMETERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class AutoTestStepResult {
  public static final String JSON_PROPERTY_TITLE = "title";
  private JsonNullable<String> title = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INFO = "info";
  private JsonNullable<String> info = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STARTED_ON = "startedOn";
  private JsonNullable<OffsetDateTime> startedOn = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_COMPLETED_ON = "completedOn";
  private JsonNullable<OffsetDateTime> completedOn = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_DURATION = "duration";
  private JsonNullable<Long> duration = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  private JsonNullable<AvailableTestResultOutcome> outcome = JsonNullable.<AvailableTestResultOutcome>undefined();

  public static final String JSON_PROPERTY_STEP_RESULTS = "stepResults";
  private JsonNullable<List<AutoTestStepResult>> stepResults = JsonNullable.<List<AutoTestStepResult>>undefined();

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  private JsonNullable<List<AttachmentApiResult>> attachments = JsonNullable.<List<AttachmentApiResult>>undefined();

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  private JsonNullable<Map<String, String>> parameters = JsonNullable.<Map<String, String>>undefined();

  public AutoTestStepResult() { 
  }

  public AutoTestStepResult title(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
    return this;
  }

  /**
   * The name of the step.
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTitle() {
        return title.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTitle_JsonNullable() {
    return title;
  }
  
  @JsonProperty(JSON_PROPERTY_TITLE)
  public void setTitle_JsonNullable(JsonNullable<String> title) {
    this.title = title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
  }


  public AutoTestStepResult description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Description of the step result.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public AutoTestStepResult info(@jakarta.annotation.Nullable String info) {
    this.info = JsonNullable.<String>of(info);
    return this;
  }

  /**
   * Extended description of the step result.
   * @return info
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getInfo() {
        return info.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getInfo_JsonNullable() {
    return info;
  }
  
  @JsonProperty(JSON_PROPERTY_INFO)
  public void setInfo_JsonNullable(JsonNullable<String> info) {
    this.info = info;
  }

  public void setInfo(@jakarta.annotation.Nullable String info) {
    this.info = JsonNullable.<String>of(info);
  }


  public AutoTestStepResult startedOn(@jakarta.annotation.Nullable OffsetDateTime startedOn) {
    this.startedOn = JsonNullable.<OffsetDateTime>of(startedOn);
    return this;
  }

  /**
   * Step start date.
   * @return startedOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getStartedOn() {
        return startedOn.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STARTED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getStartedOn_JsonNullable() {
    return startedOn;
  }
  
  @JsonProperty(JSON_PROPERTY_STARTED_ON)
  public void setStartedOn_JsonNullable(JsonNullable<OffsetDateTime> startedOn) {
    this.startedOn = startedOn;
  }

  public void setStartedOn(@jakarta.annotation.Nullable OffsetDateTime startedOn) {
    this.startedOn = JsonNullable.<OffsetDateTime>of(startedOn);
  }


  public AutoTestStepResult completedOn(@jakarta.annotation.Nullable OffsetDateTime completedOn) {
    this.completedOn = JsonNullable.<OffsetDateTime>of(completedOn);
    return this;
  }

  /**
   * Step end date.
   * @return completedOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCompletedOn() {
        return completedOn.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLETED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCompletedOn_JsonNullable() {
    return completedOn;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPLETED_ON)
  public void setCompletedOn_JsonNullable(JsonNullable<OffsetDateTime> completedOn) {
    this.completedOn = completedOn;
  }

  public void setCompletedOn(@jakarta.annotation.Nullable OffsetDateTime completedOn) {
    this.completedOn = JsonNullable.<OffsetDateTime>of(completedOn);
  }


  public AutoTestStepResult duration(@jakarta.annotation.Nullable Long duration) {
    this.duration = JsonNullable.<Long>of(duration);
    return this;
  }

  /**
   * Expected or actual duration of the test run execution in milliseconds.
   * minimum: 0
   * maximum: 43200000000
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getDuration() {
        return duration.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getDuration_JsonNullable() {
    return duration;
  }
  
  @JsonProperty(JSON_PROPERTY_DURATION)
  public void setDuration_JsonNullable(JsonNullable<Long> duration) {
    this.duration = duration;
  }

  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = JsonNullable.<Long>of(duration);
  }


  public AutoTestStepResult outcome(@jakarta.annotation.Nullable AvailableTestResultOutcome outcome) {
    this.outcome = JsonNullable.<AvailableTestResultOutcome>of(outcome);
    return this;
  }

  /**
   * Specifies the result of the autotest execution.
   * @return outcome
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public AvailableTestResultOutcome getOutcome() {
        return outcome.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<AvailableTestResultOutcome> getOutcome_JsonNullable() {
    return outcome;
  }
  
  @JsonProperty(JSON_PROPERTY_OUTCOME)
  public void setOutcome_JsonNullable(JsonNullable<AvailableTestResultOutcome> outcome) {
    this.outcome = outcome;
  }

  public void setOutcome(@jakarta.annotation.Nullable AvailableTestResultOutcome outcome) {
    this.outcome = JsonNullable.<AvailableTestResultOutcome>of(outcome);
  }


  public AutoTestStepResult stepResults(@jakarta.annotation.Nullable List<AutoTestStepResult> stepResults) {
    this.stepResults = JsonNullable.<List<AutoTestStepResult>>of(stepResults);
    return this;
  }

  public AutoTestStepResult addStepResultsItem(AutoTestStepResult stepResultsItem) {
    if (this.stepResults == null || !this.stepResults.isPresent()) {
      this.stepResults = JsonNullable.<List<AutoTestStepResult>>of(new ArrayList<>());
    }
    try {
      this.stepResults.get().add(stepResultsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Nested step results. The maximum nesting level is 15.
   * @return stepResults
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AutoTestStepResult> getStepResults() {
        return stepResults.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STEP_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AutoTestStepResult>> getStepResults_JsonNullable() {
    return stepResults;
  }
  
  @JsonProperty(JSON_PROPERTY_STEP_RESULTS)
  public void setStepResults_JsonNullable(JsonNullable<List<AutoTestStepResult>> stepResults) {
    this.stepResults = stepResults;
  }

  public void setStepResults(@jakarta.annotation.Nullable List<AutoTestStepResult> stepResults) {
    this.stepResults = JsonNullable.<List<AutoTestStepResult>>of(stepResults);
  }


  public AutoTestStepResult attachments(@jakarta.annotation.Nullable List<AttachmentApiResult> attachments) {
    this.attachments = JsonNullable.<List<AttachmentApiResult>>of(attachments);
    return this;
  }

  public AutoTestStepResult addAttachmentsItem(AttachmentApiResult attachmentsItem) {
    if (this.attachments == null || !this.attachments.isPresent()) {
      this.attachments = JsonNullable.<List<AttachmentApiResult>>of(new ArrayList<>());
    }
    try {
      this.attachments.get().add(attachmentsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * /// &lt;summary&gt; Specifies an attachment GUID. Multiple values can be sent. &lt;/summary&gt;
   * @return attachments
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AttachmentApiResult> getAttachments() {
        return attachments.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AttachmentApiResult>> getAttachments_JsonNullable() {
    return attachments;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  public void setAttachments_JsonNullable(JsonNullable<List<AttachmentApiResult>> attachments) {
    this.attachments = attachments;
  }

  public void setAttachments(@jakarta.annotation.Nullable List<AttachmentApiResult> attachments) {
    this.attachments = JsonNullable.<List<AttachmentApiResult>>of(attachments);
  }


  public AutoTestStepResult parameters(@jakarta.annotation.Nullable Map<String, String> parameters) {
    this.parameters = JsonNullable.<Map<String, String>>of(parameters);
    return this;
  }

  public AutoTestStepResult putParametersItem(String key, String parametersItem) {
    if (this.parameters == null || !this.parameters.isPresent()) {
      this.parameters = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.parameters.get().put(key, parametersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * \&quot;&lt;b&gt;parameter&lt;/b&gt;\&quot;: \&quot;&lt;b&gt;value&lt;/b&gt;\&quot; pair with arbitrary custom parameters. Multiple parameters can be sent.
   * @return parameters
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getParameters() {
        return parameters.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getParameters_JsonNullable() {
    return parameters;
  }
  
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  public void setParameters_JsonNullable(JsonNullable<Map<String, String>> parameters) {
    this.parameters = parameters;
  }

  public void setParameters(@jakarta.annotation.Nullable Map<String, String> parameters) {
    this.parameters = JsonNullable.<Map<String, String>>of(parameters);
  }


  /**
   * Return true if this AutoTestStepResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoTestStepResult autoTestStepResult = (AutoTestStepResult) o;
    return equalsNullable(this.title, autoTestStepResult.title) &&
        equalsNullable(this.description, autoTestStepResult.description) &&
        equalsNullable(this.info, autoTestStepResult.info) &&
        equalsNullable(this.startedOn, autoTestStepResult.startedOn) &&
        equalsNullable(this.completedOn, autoTestStepResult.completedOn) &&
        equalsNullable(this.duration, autoTestStepResult.duration) &&
        equalsNullable(this.outcome, autoTestStepResult.outcome) &&
        equalsNullable(this.stepResults, autoTestStepResult.stepResults) &&
        equalsNullable(this.attachments, autoTestStepResult.attachments) &&
        equalsNullable(this.parameters, autoTestStepResult.parameters);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(title), hashCodeNullable(description), hashCodeNullable(info), hashCodeNullable(startedOn), hashCodeNullable(completedOn), hashCodeNullable(duration), hashCodeNullable(outcome), hashCodeNullable(stepResults), hashCodeNullable(attachments), hashCodeNullable(parameters));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoTestStepResult {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    startedOn: ").append(toIndentedString(startedOn)).append("\n");
    sb.append("    completedOn: ").append(toIndentedString(completedOn)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    stepResults: ").append(toIndentedString(stepResults)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

