/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.CustomAttributeOptionApiResult;
import ru.testit.adaptersapi.model.CustomAttributeType;
import ru.testit.adaptersapi.model.ProjectShortestApiResult;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * CustomAttributeSearchApiResult
 */
@JsonPropertyOrder({
  CustomAttributeSearchApiResult.JSON_PROPERTY_WORK_ITEM_USAGE,
  CustomAttributeSearchApiResult.JSON_PROPERTY_TEST_PLAN_USAGE,
  CustomAttributeSearchApiResult.JSON_PROPERTY_ID,
  CustomAttributeSearchApiResult.JSON_PROPERTY_OPTIONS,
  CustomAttributeSearchApiResult.JSON_PROPERTY_TYPE,
  CustomAttributeSearchApiResult.JSON_PROPERTY_IS_DELETED,
  CustomAttributeSearchApiResult.JSON_PROPERTY_NAME,
  CustomAttributeSearchApiResult.JSON_PROPERTY_IS_ENABLED,
  CustomAttributeSearchApiResult.JSON_PROPERTY_IS_REQUIRED,
  CustomAttributeSearchApiResult.JSON_PROPERTY_IS_GLOBAL,
  CustomAttributeSearchApiResult.JSON_PROPERTY_IS_READ_ONLY,
  CustomAttributeSearchApiResult.JSON_PROPERTY_IS_SYSTEM,
  CustomAttributeSearchApiResult.JSON_PROPERTY_TARGETS,
  CustomAttributeSearchApiResult.JSON_PROPERTY_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CustomAttributeSearchApiResult {
  public static final String JSON_PROPERTY_WORK_ITEM_USAGE = "workItemUsage";
  @jakarta.annotation.Nonnull
  private List<ProjectShortestApiResult> workItemUsage = new ArrayList<>();

  public static final String JSON_PROPERTY_TEST_PLAN_USAGE = "testPlanUsage";
  @jakarta.annotation.Nonnull
  private List<ProjectShortestApiResult> testPlanUsage = new ArrayList<>();

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @jakarta.annotation.Nonnull
  private List<CustomAttributeOptionApiResult> options = new ArrayList<>();

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private CustomAttributeType type;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nonnull
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_IS_ENABLED = "isEnabled";
  @jakarta.annotation.Nonnull
  private Boolean isEnabled;

  public static final String JSON_PROPERTY_IS_REQUIRED = "isRequired";
  @jakarta.annotation.Nonnull
  private Boolean isRequired;

  public static final String JSON_PROPERTY_IS_GLOBAL = "isGlobal";
  @jakarta.annotation.Nonnull
  private Boolean isGlobal;

  public static final String JSON_PROPERTY_IS_READ_ONLY = "isReadOnly";
  @jakarta.annotation.Nonnull
  private Boolean isReadOnly;

  public static final String JSON_PROPERTY_IS_SYSTEM = "isSystem";
  @jakarta.annotation.Nonnull
  private Boolean isSystem;

  public static final String JSON_PROPERTY_TARGETS = "targets";
  @jakarta.annotation.Nonnull
  private List<String> targets = new ArrayList<>();

  public static final String JSON_PROPERTY_CODE = "code";
  private JsonNullable<String> code = JsonNullable.<String>undefined();

  public CustomAttributeSearchApiResult() { 
  }

  public CustomAttributeSearchApiResult workItemUsage(@jakarta.annotation.Nonnull List<ProjectShortestApiResult> workItemUsage) {
    this.workItemUsage = workItemUsage;
    return this;
  }

  public CustomAttributeSearchApiResult addWorkItemUsageItem(ProjectShortestApiResult workItemUsageItem) {
    if (this.workItemUsage == null) {
      this.workItemUsage = new ArrayList<>();
    }
    this.workItemUsage.add(workItemUsageItem);
    return this;
  }

  /**
   * Projects where attribute is used in work items
   * @return workItemUsage
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WORK_ITEM_USAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ProjectShortestApiResult> getWorkItemUsage() {
    return workItemUsage;
  }


  @JsonProperty(JSON_PROPERTY_WORK_ITEM_USAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkItemUsage(@jakarta.annotation.Nonnull List<ProjectShortestApiResult> workItemUsage) {
    this.workItemUsage = workItemUsage;
  }


  public CustomAttributeSearchApiResult testPlanUsage(@jakarta.annotation.Nonnull List<ProjectShortestApiResult> testPlanUsage) {
    this.testPlanUsage = testPlanUsage;
    return this;
  }

  public CustomAttributeSearchApiResult addTestPlanUsageItem(ProjectShortestApiResult testPlanUsageItem) {
    if (this.testPlanUsage == null) {
      this.testPlanUsage = new ArrayList<>();
    }
    this.testPlanUsage.add(testPlanUsageItem);
    return this;
  }

  /**
   * Projects where attribute is used in test plans
   * @return testPlanUsage
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEST_PLAN_USAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ProjectShortestApiResult> getTestPlanUsage() {
    return testPlanUsage;
  }


  @JsonProperty(JSON_PROPERTY_TEST_PLAN_USAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTestPlanUsage(@jakarta.annotation.Nonnull List<ProjectShortestApiResult> testPlanUsage) {
    this.testPlanUsage = testPlanUsage;
  }


  public CustomAttributeSearchApiResult id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Unique ID of the attribute
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public CustomAttributeSearchApiResult options(@jakarta.annotation.Nonnull List<CustomAttributeOptionApiResult> options) {
    this.options = options;
    return this;
  }

  public CustomAttributeSearchApiResult addOptionsItem(CustomAttributeOptionApiResult optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

  /**
   * Collection of the attribute options   Available for attributes of type &#x60;options&#x60; and &#x60;multiple options&#x60; only
   * @return options
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CustomAttributeOptionApiResult> getOptions() {
    return options;
  }


  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOptions(@jakarta.annotation.Nonnull List<CustomAttributeOptionApiResult> options) {
    this.options = options;
  }


  public CustomAttributeSearchApiResult type(@jakarta.annotation.Nonnull CustomAttributeType type) {
    this.type = type;
    return this;
  }

  /**
   * Type of the attribute
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CustomAttributeType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull CustomAttributeType type) {
    this.type = type;
  }


  public CustomAttributeSearchApiResult isDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Indicates if the attribute is deleted
   * @return isDeleted
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public CustomAttributeSearchApiResult name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the attribute
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public CustomAttributeSearchApiResult isEnabled(@jakarta.annotation.Nonnull Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

  /**
   * Indicates if the attribute is enabled
   * @return isEnabled
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsEnabled() {
    return isEnabled;
  }


  @JsonProperty(JSON_PROPERTY_IS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsEnabled(@jakarta.annotation.Nonnull Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }


  public CustomAttributeSearchApiResult isRequired(@jakarta.annotation.Nonnull Boolean isRequired) {
    this.isRequired = isRequired;
    return this;
  }

  /**
   * Indicates if the attribute value is mandatory to specify
   * @return isRequired
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsRequired() {
    return isRequired;
  }


  @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsRequired(@jakarta.annotation.Nonnull Boolean isRequired) {
    this.isRequired = isRequired;
  }


  public CustomAttributeSearchApiResult isGlobal(@jakarta.annotation.Nonnull Boolean isGlobal) {
    this.isGlobal = isGlobal;
    return this;
  }

  /**
   * Indicates if the attribute is available across all projects
   * @return isGlobal
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_GLOBAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsGlobal() {
    return isGlobal;
  }


  @JsonProperty(JSON_PROPERTY_IS_GLOBAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsGlobal(@jakarta.annotation.Nonnull Boolean isGlobal) {
    this.isGlobal = isGlobal;
  }


  public CustomAttributeSearchApiResult isReadOnly(@jakarta.annotation.Nonnull Boolean isReadOnly) {
    this.isReadOnly = isReadOnly;
    return this;
  }

  /**
   * Indicates if the attribute is read-only
   * @return isReadOnly
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_READ_ONLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsReadOnly() {
    return isReadOnly;
  }


  @JsonProperty(JSON_PROPERTY_IS_READ_ONLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsReadOnly(@jakarta.annotation.Nonnull Boolean isReadOnly) {
    this.isReadOnly = isReadOnly;
  }


  public CustomAttributeSearchApiResult isSystem(@jakarta.annotation.Nonnull Boolean isSystem) {
    this.isSystem = isSystem;
    return this;
  }

  /**
   * Indicates if the attribute is system
   * @return isSystem
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsSystem() {
    return isSystem;
  }


  @JsonProperty(JSON_PROPERTY_IS_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsSystem(@jakarta.annotation.Nonnull Boolean isSystem) {
    this.isSystem = isSystem;
  }


  public CustomAttributeSearchApiResult targets(@jakarta.annotation.Nonnull List<String> targets) {
    this.targets = targets;
    return this;
  }

  public CustomAttributeSearchApiResult addTargetsItem(String targetsItem) {
    if (this.targets == null) {
      this.targets = new ArrayList<>();
    }
    this.targets.add(targetsItem);
    return this;
  }

  /**
   * Collection of the attribute targets   Defines where the attribute can be used (e.g., TestCases, AutoTestCases, TestPlans)
   * @return targets
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TARGETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getTargets() {
    return targets;
  }


  @JsonProperty(JSON_PROPERTY_TARGETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTargets(@jakarta.annotation.Nonnull List<String> targets) {
    this.targets = targets;
  }


  public CustomAttributeSearchApiResult code(@jakarta.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
    return this;
  }

  /**
   * Optional code identifier for the attribute
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getCode() {
        return code.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCode_JsonNullable() {
    return code;
  }
  
  @JsonProperty(JSON_PROPERTY_CODE)
  public void setCode_JsonNullable(JsonNullable<String> code) {
    this.code = code;
  }

  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
  }


  /**
   * Return true if this CustomAttributeSearchApiResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomAttributeSearchApiResult customAttributeSearchApiResult = (CustomAttributeSearchApiResult) o;
    return Objects.equals(this.workItemUsage, customAttributeSearchApiResult.workItemUsage) &&
        Objects.equals(this.testPlanUsage, customAttributeSearchApiResult.testPlanUsage) &&
        Objects.equals(this.id, customAttributeSearchApiResult.id) &&
        Objects.equals(this.options, customAttributeSearchApiResult.options) &&
        Objects.equals(this.type, customAttributeSearchApiResult.type) &&
        Objects.equals(this.isDeleted, customAttributeSearchApiResult.isDeleted) &&
        Objects.equals(this.name, customAttributeSearchApiResult.name) &&
        Objects.equals(this.isEnabled, customAttributeSearchApiResult.isEnabled) &&
        Objects.equals(this.isRequired, customAttributeSearchApiResult.isRequired) &&
        Objects.equals(this.isGlobal, customAttributeSearchApiResult.isGlobal) &&
        Objects.equals(this.isReadOnly, customAttributeSearchApiResult.isReadOnly) &&
        Objects.equals(this.isSystem, customAttributeSearchApiResult.isSystem) &&
        Objects.equals(this.targets, customAttributeSearchApiResult.targets) &&
        equalsNullable(this.code, customAttributeSearchApiResult.code);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(workItemUsage, testPlanUsage, id, options, type, isDeleted, name, isEnabled, isRequired, isGlobal, isReadOnly, isSystem, targets, hashCodeNullable(code));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomAttributeSearchApiResult {\n");
    sb.append("    workItemUsage: ").append(toIndentedString(workItemUsage)).append("\n");
    sb.append("    testPlanUsage: ").append(toIndentedString(testPlanUsage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
    sb.append("    isGlobal: ").append(toIndentedString(isGlobal)).append("\n");
    sb.append("    isReadOnly: ").append(toIndentedString(isReadOnly)).append("\n");
    sb.append("    isSystem: ").append(toIndentedString(isSystem)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

