/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.CustomAttributeType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * CustomAttributeSearchApiModel
 */
@JsonPropertyOrder({
  CustomAttributeSearchApiModel.JSON_PROPERTY_NAME,
  CustomAttributeSearchApiModel.JSON_PROPERTY_PROJECT_IDS,
  CustomAttributeSearchApiModel.JSON_PROPERTY_CUSTOM_ATTRIBUTE_IDS,
  CustomAttributeSearchApiModel.JSON_PROPERTY_CUSTOM_ATTRIBUTE_TYPES,
  CustomAttributeSearchApiModel.JSON_PROPERTY_IS_GLOBAL,
  CustomAttributeSearchApiModel.JSON_PROPERTY_IS_DELETED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CustomAttributeSearchApiModel {
  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROJECT_IDS = "projectIds";
  private JsonNullable<Set<UUID>> projectIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTE_IDS = "customAttributeIds";
  private JsonNullable<Set<UUID>> customAttributeIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTE_TYPES = "customAttributeTypes";
  private JsonNullable<Set<CustomAttributeType>> customAttributeTypes = JsonNullable.<Set<CustomAttributeType>>undefined();

  public static final String JSON_PROPERTY_IS_GLOBAL = "isGlobal";
  private JsonNullable<Boolean> isGlobal = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  private JsonNullable<Boolean> isDeleted = JsonNullable.<Boolean>undefined();

  public CustomAttributeSearchApiModel() { 
  }

  public CustomAttributeSearchApiModel name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Name of attribute
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public CustomAttributeSearchApiModel projectIds(@jakarta.annotation.Nullable Set<UUID> projectIds) {
    this.projectIds = JsonNullable.<Set<UUID>>of(projectIds);
    return this;
  }

  public CustomAttributeSearchApiModel addProjectIdsItem(UUID projectIdsItem) {
    if (this.projectIds == null || !this.projectIds.isPresent()) {
      this.projectIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.projectIds.get().add(projectIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Unique IDs of projects where attribute is in use
   * @return projectIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getProjectIds() {
        return projectIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROJECT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getProjectIds_JsonNullable() {
    return projectIds;
  }
  
  @JsonProperty(JSON_PROPERTY_PROJECT_IDS)
  public void setProjectIds_JsonNullable(JsonNullable<Set<UUID>> projectIds) {
    this.projectIds = projectIds;
  }

  public void setProjectIds(@jakarta.annotation.Nullable Set<UUID> projectIds) {
    this.projectIds = JsonNullable.<Set<UUID>>of(projectIds);
  }


  public CustomAttributeSearchApiModel customAttributeIds(@jakarta.annotation.Nullable Set<UUID> customAttributeIds) {
    this.customAttributeIds = JsonNullable.<Set<UUID>>of(customAttributeIds);
    return this;
  }

  public CustomAttributeSearchApiModel addCustomAttributeIdsItem(UUID customAttributeIdsItem) {
    if (this.customAttributeIds == null || !this.customAttributeIds.isPresent()) {
      this.customAttributeIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.customAttributeIds.get().add(customAttributeIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Unique IDs of attributes for search restriction
   * @return customAttributeIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getCustomAttributeIds() {
        return customAttributeIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getCustomAttributeIds_JsonNullable() {
    return customAttributeIds;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTE_IDS)
  public void setCustomAttributeIds_JsonNullable(JsonNullable<Set<UUID>> customAttributeIds) {
    this.customAttributeIds = customAttributeIds;
  }

  public void setCustomAttributeIds(@jakarta.annotation.Nullable Set<UUID> customAttributeIds) {
    this.customAttributeIds = JsonNullable.<Set<UUID>>of(customAttributeIds);
  }


  public CustomAttributeSearchApiModel customAttributeTypes(@jakarta.annotation.Nullable Set<CustomAttributeType> customAttributeTypes) {
    this.customAttributeTypes = JsonNullable.<Set<CustomAttributeType>>of(customAttributeTypes);
    return this;
  }

  public CustomAttributeSearchApiModel addCustomAttributeTypesItem(CustomAttributeType customAttributeTypesItem) {
    if (this.customAttributeTypes == null || !this.customAttributeTypes.isPresent()) {
      this.customAttributeTypes = JsonNullable.<Set<CustomAttributeType>>of(new LinkedHashSet<>());
    }
    try {
      this.customAttributeTypes.get().add(customAttributeTypesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of attribute types
   * @return customAttributeTypes
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<CustomAttributeType> getCustomAttributeTypes() {
        return customAttributeTypes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<CustomAttributeType>> getCustomAttributeTypes_JsonNullable() {
    return customAttributeTypes;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTE_TYPES)
  public void setCustomAttributeTypes_JsonNullable(JsonNullable<Set<CustomAttributeType>> customAttributeTypes) {
    this.customAttributeTypes = customAttributeTypes;
  }

  public void setCustomAttributeTypes(@jakarta.annotation.Nullable Set<CustomAttributeType> customAttributeTypes) {
    this.customAttributeTypes = JsonNullable.<Set<CustomAttributeType>>of(customAttributeTypes);
  }


  public CustomAttributeSearchApiModel isGlobal(@jakarta.annotation.Nullable Boolean isGlobal) {
    this.isGlobal = JsonNullable.<Boolean>of(isGlobal);
    return this;
  }

  /**
   * Indicates whether the attribute is available across all projects
   * @return isGlobal
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsGlobal() {
        return isGlobal.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_GLOBAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsGlobal_JsonNullable() {
    return isGlobal;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_GLOBAL)
  public void setIsGlobal_JsonNullable(JsonNullable<Boolean> isGlobal) {
    this.isGlobal = isGlobal;
  }

  public void setIsGlobal(@jakarta.annotation.Nullable Boolean isGlobal) {
    this.isGlobal = JsonNullable.<Boolean>of(isGlobal);
  }


  public CustomAttributeSearchApiModel isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
    return this;
  }

  /**
   * Indicates whether the attribute is deleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsDeleted() {
        return isDeleted.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsDeleted_JsonNullable() {
    return isDeleted;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  public void setIsDeleted_JsonNullable(JsonNullable<Boolean> isDeleted) {
    this.isDeleted = isDeleted;
  }

  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
  }


  /**
   * Return true if this CustomAttributeSearchApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomAttributeSearchApiModel customAttributeSearchApiModel = (CustomAttributeSearchApiModel) o;
    return equalsNullable(this.name, customAttributeSearchApiModel.name) &&
        equalsNullable(this.projectIds, customAttributeSearchApiModel.projectIds) &&
        equalsNullable(this.customAttributeIds, customAttributeSearchApiModel.customAttributeIds) &&
        equalsNullable(this.customAttributeTypes, customAttributeSearchApiModel.customAttributeTypes) &&
        equalsNullable(this.isGlobal, customAttributeSearchApiModel.isGlobal) &&
        equalsNullable(this.isDeleted, customAttributeSearchApiModel.isDeleted);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(name), hashCodeNullable(projectIds), hashCodeNullable(customAttributeIds), hashCodeNullable(customAttributeTypes), hashCodeNullable(isGlobal), hashCodeNullable(isDeleted));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomAttributeSearchApiModel {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    customAttributeIds: ").append(toIndentedString(customAttributeIds)).append("\n");
    sb.append("    customAttributeTypes: ").append(toIndentedString(customAttributeTypes)).append("\n");
    sb.append("    isGlobal: ").append(toIndentedString(isGlobal)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

