/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.CustomAttributeApiResult;
import ru.testit.adaptersapi.model.WorkflowApiResult;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * DetailedProjectApiResult
 */
@JsonPropertyOrder({
  DetailedProjectApiResult.JSON_PROPERTY_WORKFLOW,
  DetailedProjectApiResult.JSON_PROPERTY_ID,
  DetailedProjectApiResult.JSON_PROPERTY_NAME,
  DetailedProjectApiResult.JSON_PROPERTY_IS_FAVORITE,
  DetailedProjectApiResult.JSON_PROPERTY_IS_DELETED,
  DetailedProjectApiResult.JSON_PROPERTY_GLOBAL_ID,
  DetailedProjectApiResult.JSON_PROPERTY_WORKFLOW_ID,
  DetailedProjectApiResult.JSON_PROPERTY_ATTRIBUTES_SCHEME,
  DetailedProjectApiResult.JSON_PROPERTY_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class DetailedProjectApiResult {
  public static final String JSON_PROPERTY_WORKFLOW = "workflow";
  @jakarta.annotation.Nonnull
  private WorkflowApiResult workflow;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_IS_FAVORITE = "isFavorite";
  @jakarta.annotation.Nonnull
  private Boolean isFavorite;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nonnull
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_GLOBAL_ID = "globalId";
  @jakarta.annotation.Nonnull
  private Long globalId;

  public static final String JSON_PROPERTY_WORKFLOW_ID = "workflowId";
  @jakarta.annotation.Nonnull
  private UUID workflowId;

  public static final String JSON_PROPERTY_ATTRIBUTES_SCHEME = "attributesScheme";
  private JsonNullable<List<CustomAttributeApiResult>> attributesScheme = JsonNullable.<List<CustomAttributeApiResult>>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public DetailedProjectApiResult() { 
  }

  public DetailedProjectApiResult workflow(@jakarta.annotation.Nonnull WorkflowApiResult workflow) {
    this.workflow = workflow;
    return this;
  }

  /**
   * ID of the workflow used in project
   * @return workflow
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WORKFLOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WorkflowApiResult getWorkflow() {
    return workflow;
  }


  @JsonProperty(JSON_PROPERTY_WORKFLOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkflow(@jakarta.annotation.Nonnull WorkflowApiResult workflow) {
    this.workflow = workflow;
  }


  public DetailedProjectApiResult id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Unique ID of the project
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public DetailedProjectApiResult name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the project
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public DetailedProjectApiResult isFavorite(@jakarta.annotation.Nonnull Boolean isFavorite) {
    this.isFavorite = isFavorite;
    return this;
  }

  /**
   * Indicates if the project is marked as favorite
   * @return isFavorite
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsFavorite() {
    return isFavorite;
  }


  @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsFavorite(@jakarta.annotation.Nonnull Boolean isFavorite) {
    this.isFavorite = isFavorite;
  }


  public DetailedProjectApiResult isDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Indicates if the project is deleted
   * @return isDeleted
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public DetailedProjectApiResult globalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
    return this;
  }

  /**
   * Global ID of the project
   * @return globalId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getGlobalId() {
    return globalId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGlobalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
  }


  public DetailedProjectApiResult workflowId(@jakarta.annotation.Nonnull UUID workflowId) {
    this.workflowId = workflowId;
    return this;
  }

  /**
   * ID of the workflow used in project
   * @return workflowId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WORKFLOW_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getWorkflowId() {
    return workflowId;
  }


  @JsonProperty(JSON_PROPERTY_WORKFLOW_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkflowId(@jakarta.annotation.Nonnull UUID workflowId) {
    this.workflowId = workflowId;
  }


  public DetailedProjectApiResult attributesScheme(@jakarta.annotation.Nullable List<CustomAttributeApiResult> attributesScheme) {
    this.attributesScheme = JsonNullable.<List<CustomAttributeApiResult>>of(attributesScheme);
    return this;
  }

  public DetailedProjectApiResult addAttributesSchemeItem(CustomAttributeApiResult attributesSchemeItem) {
    if (this.attributesScheme == null || !this.attributesScheme.isPresent()) {
      this.attributesScheme = JsonNullable.<List<CustomAttributeApiResult>>of(new ArrayList<>());
    }
    try {
      this.attributesScheme.get().add(attributesSchemeItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of the project attributes
   * @return attributesScheme
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<CustomAttributeApiResult> getAttributesScheme() {
        return attributesScheme.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<CustomAttributeApiResult>> getAttributesScheme_JsonNullable() {
    return attributesScheme;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES_SCHEME)
  public void setAttributesScheme_JsonNullable(JsonNullable<List<CustomAttributeApiResult>> attributesScheme) {
    this.attributesScheme = attributesScheme;
  }

  public void setAttributesScheme(@jakarta.annotation.Nullable List<CustomAttributeApiResult> attributesScheme) {
    this.attributesScheme = JsonNullable.<List<CustomAttributeApiResult>>of(attributesScheme);
  }


  public DetailedProjectApiResult description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Description of the project
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  /**
   * Return true if this DetailedProjectApiResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedProjectApiResult detailedProjectApiResult = (DetailedProjectApiResult) o;
    return Objects.equals(this.workflow, detailedProjectApiResult.workflow) &&
        Objects.equals(this.id, detailedProjectApiResult.id) &&
        Objects.equals(this.name, detailedProjectApiResult.name) &&
        Objects.equals(this.isFavorite, detailedProjectApiResult.isFavorite) &&
        Objects.equals(this.isDeleted, detailedProjectApiResult.isDeleted) &&
        Objects.equals(this.globalId, detailedProjectApiResult.globalId) &&
        Objects.equals(this.workflowId, detailedProjectApiResult.workflowId) &&
        equalsNullable(this.attributesScheme, detailedProjectApiResult.attributesScheme) &&
        equalsNullable(this.description, detailedProjectApiResult.description);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflow, id, name, isFavorite, isDeleted, globalId, workflowId, hashCodeNullable(attributesScheme), hashCodeNullable(description));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedProjectApiResult {\n");
    sb.append("    workflow: ").append(toIndentedString(workflow)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isFavorite: ").append(toIndentedString(isFavorite)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    globalId: ").append(toIndentedString(globalId)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    attributesScheme: ").append(toIndentedString(attributesScheme)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

