/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.CustomAttributeOptionUpdateApiModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * GlobalCustomAttributeUpdateApiModel
 */
@JsonPropertyOrder({
  GlobalCustomAttributeUpdateApiModel.JSON_PROPERTY_NAME,
  GlobalCustomAttributeUpdateApiModel.JSON_PROPERTY_OPTIONS,
  GlobalCustomAttributeUpdateApiModel.JSON_PROPERTY_IS_ENABLED,
  GlobalCustomAttributeUpdateApiModel.JSON_PROPERTY_IS_REQUIRED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GlobalCustomAttributeUpdateApiModel {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  private JsonNullable<List<CustomAttributeOptionUpdateApiModel>> options = JsonNullable.<List<CustomAttributeOptionUpdateApiModel>>undefined();

  public static final String JSON_PROPERTY_IS_ENABLED = "isEnabled";
  private JsonNullable<Boolean> isEnabled = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_IS_REQUIRED = "isRequired";
  private JsonNullable<Boolean> isRequired = JsonNullable.<Boolean>undefined();

  public GlobalCustomAttributeUpdateApiModel() { 
  }

  public GlobalCustomAttributeUpdateApiModel name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of attribute
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public GlobalCustomAttributeUpdateApiModel options(@jakarta.annotation.Nullable List<CustomAttributeOptionUpdateApiModel> options) {
    this.options = JsonNullable.<List<CustomAttributeOptionUpdateApiModel>>of(options);
    return this;
  }

  public GlobalCustomAttributeUpdateApiModel addOptionsItem(CustomAttributeOptionUpdateApiModel optionsItem) {
    if (this.options == null || !this.options.isPresent()) {
      this.options = JsonNullable.<List<CustomAttributeOptionUpdateApiModel>>of(new ArrayList<>());
    }
    try {
      this.options.get().add(optionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of attribute options   Available for attributes of type &#x60;options&#x60; and &#x60;multiple options&#x60; only
   * @return options
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<CustomAttributeOptionUpdateApiModel> getOptions() {
        return options.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<CustomAttributeOptionUpdateApiModel>> getOptions_JsonNullable() {
    return options;
  }
  
  @JsonProperty(JSON_PROPERTY_OPTIONS)
  public void setOptions_JsonNullable(JsonNullable<List<CustomAttributeOptionUpdateApiModel>> options) {
    this.options = options;
  }

  public void setOptions(@jakarta.annotation.Nullable List<CustomAttributeOptionUpdateApiModel> options) {
    this.options = JsonNullable.<List<CustomAttributeOptionUpdateApiModel>>of(options);
  }


  public GlobalCustomAttributeUpdateApiModel isEnabled(@jakarta.annotation.Nullable Boolean isEnabled) {
    this.isEnabled = JsonNullable.<Boolean>of(isEnabled);
    return this;
  }

  /**
   * Indicates whether the attribute is available
   * @return isEnabled
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsEnabled() {
        return isEnabled.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsEnabled_JsonNullable() {
    return isEnabled;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_ENABLED)
  public void setIsEnabled_JsonNullable(JsonNullable<Boolean> isEnabled) {
    this.isEnabled = isEnabled;
  }

  public void setIsEnabled(@jakarta.annotation.Nullable Boolean isEnabled) {
    this.isEnabled = JsonNullable.<Boolean>of(isEnabled);
  }


  public GlobalCustomAttributeUpdateApiModel isRequired(@jakarta.annotation.Nullable Boolean isRequired) {
    this.isRequired = JsonNullable.<Boolean>of(isRequired);
    return this;
  }

  /**
   * Indicates whether the attribute value is mandatory to specify
   * @return isRequired
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsRequired() {
        return isRequired.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsRequired_JsonNullable() {
    return isRequired;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
  public void setIsRequired_JsonNullable(JsonNullable<Boolean> isRequired) {
    this.isRequired = isRequired;
  }

  public void setIsRequired(@jakarta.annotation.Nullable Boolean isRequired) {
    this.isRequired = JsonNullable.<Boolean>of(isRequired);
  }


  /**
   * Return true if this GlobalCustomAttributeUpdateApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalCustomAttributeUpdateApiModel globalCustomAttributeUpdateApiModel = (GlobalCustomAttributeUpdateApiModel) o;
    return Objects.equals(this.name, globalCustomAttributeUpdateApiModel.name) &&
        equalsNullable(this.options, globalCustomAttributeUpdateApiModel.options) &&
        equalsNullable(this.isEnabled, globalCustomAttributeUpdateApiModel.isEnabled) &&
        equalsNullable(this.isRequired, globalCustomAttributeUpdateApiModel.isRequired);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, hashCodeNullable(options), hashCodeNullable(isEnabled), hashCodeNullable(isRequired));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalCustomAttributeUpdateApiModel {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

