/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.GuidExtractionModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * ManualRerunTestResultApiModel
 */
@JsonPropertyOrder({
  ManualRerunTestResultApiModel.JSON_PROPERTY_TEST_RESULT_IDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class ManualRerunTestResultApiModel {
  public static final String JSON_PROPERTY_TEST_RESULT_IDS = "testResultIds";
  private JsonNullable<GuidExtractionModel> testResultIds = JsonNullable.<GuidExtractionModel>undefined();

  public ManualRerunTestResultApiModel() { 
  }

  public ManualRerunTestResultApiModel testResultIds(@jakarta.annotation.Nullable GuidExtractionModel testResultIds) {
    this.testResultIds = JsonNullable.<GuidExtractionModel>of(testResultIds);
    return this;
  }

  /**
   * Set of extracted test result IDs
   * @return testResultIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public GuidExtractionModel getTestResultIds() {
        return testResultIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEST_RESULT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<GuidExtractionModel> getTestResultIds_JsonNullable() {
    return testResultIds;
  }
  
  @JsonProperty(JSON_PROPERTY_TEST_RESULT_IDS)
  public void setTestResultIds_JsonNullable(JsonNullable<GuidExtractionModel> testResultIds) {
    this.testResultIds = testResultIds;
  }

  public void setTestResultIds(@jakarta.annotation.Nullable GuidExtractionModel testResultIds) {
    this.testResultIds = JsonNullable.<GuidExtractionModel>of(testResultIds);
  }


  /**
   * Return true if this ManualRerunTestResultApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManualRerunTestResultApiModel manualRerunTestResultApiModel = (ManualRerunTestResultApiModel) o;
    return equalsNullable(this.testResultIds, manualRerunTestResultApiModel.testResultIds);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(testResultIds));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManualRerunTestResultApiModel {\n");
    sb.append("    testResultIds: ").append(toIndentedString(testResultIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

