/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * ParameterIterationModel
 */
@JsonPropertyOrder({
  ParameterIterationModel.JSON_PROPERTY_ID,
  ParameterIterationModel.JSON_PROPERTY_SHARED_STEP_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class ParameterIterationModel {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_SHARED_STEP_ID = "sharedStepId";
  private JsonNullable<UUID> sharedStepId = JsonNullable.<UUID>undefined();

  public ParameterIterationModel() { 
  }

  public ParameterIterationModel id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public ParameterIterationModel sharedStepId(@jakarta.annotation.Nullable UUID sharedStepId) {
    this.sharedStepId = JsonNullable.<UUID>of(sharedStepId);
    return this;
  }

  /**
   * Get sharedStepId
   * @return sharedStepId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public UUID getSharedStepId() {
        return sharedStepId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SHARED_STEP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getSharedStepId_JsonNullable() {
    return sharedStepId;
  }
  
  @JsonProperty(JSON_PROPERTY_SHARED_STEP_ID)
  public void setSharedStepId_JsonNullable(JsonNullable<UUID> sharedStepId) {
    this.sharedStepId = sharedStepId;
  }

  public void setSharedStepId(@jakarta.annotation.Nullable UUID sharedStepId) {
    this.sharedStepId = JsonNullable.<UUID>of(sharedStepId);
  }


  /**
   * Return true if this ParameterIterationModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterIterationModel parameterIterationModel = (ParameterIterationModel) o;
    return Objects.equals(this.id, parameterIterationModel.id) &&
        equalsNullable(this.sharedStepId, parameterIterationModel.sharedStepId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hashCodeNullable(sharedStepId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterIterationModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sharedStepId: ").append(toIndentedString(sharedStepId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

