/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.DateTimeRangeSelectorModel;
import ru.testit.adaptersapi.model.Int32RangeSelectorModel;
import ru.testit.adaptersapi.model.ProjectTypeModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * ProjectsFilterModel
 */
@JsonPropertyOrder({
  ProjectsFilterModel.JSON_PROPERTY_NAME,
  ProjectsFilterModel.JSON_PROPERTY_IS_FAVORITE,
  ProjectsFilterModel.JSON_PROPERTY_IS_DELETED,
  ProjectsFilterModel.JSON_PROPERTY_TEST_CASES_COUNT,
  ProjectsFilterModel.JSON_PROPERTY_CHECKLISTS_COUNT,
  ProjectsFilterModel.JSON_PROPERTY_SHARED_STEPS_COUNT,
  ProjectsFilterModel.JSON_PROPERTY_AUTOTESTS_COUNT,
  ProjectsFilterModel.JSON_PROPERTY_GLOBAL_IDS,
  ProjectsFilterModel.JSON_PROPERTY_CREATED_DATE,
  ProjectsFilterModel.JSON_PROPERTY_CREATED_BY_IDS,
  ProjectsFilterModel.JSON_PROPERTY_TYPES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class ProjectsFilterModel {
  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_FAVORITE = "isFavorite";
  private JsonNullable<Boolean> isFavorite = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  private JsonNullable<Boolean> isDeleted = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_TEST_CASES_COUNT = "testCasesCount";
  private JsonNullable<Int32RangeSelectorModel> testCasesCount = JsonNullable.<Int32RangeSelectorModel>undefined();

  public static final String JSON_PROPERTY_CHECKLISTS_COUNT = "checklistsCount";
  private JsonNullable<Int32RangeSelectorModel> checklistsCount = JsonNullable.<Int32RangeSelectorModel>undefined();

  public static final String JSON_PROPERTY_SHARED_STEPS_COUNT = "sharedStepsCount";
  private JsonNullable<Int32RangeSelectorModel> sharedStepsCount = JsonNullable.<Int32RangeSelectorModel>undefined();

  public static final String JSON_PROPERTY_AUTOTESTS_COUNT = "autotestsCount";
  private JsonNullable<Int32RangeSelectorModel> autotestsCount = JsonNullable.<Int32RangeSelectorModel>undefined();

  public static final String JSON_PROPERTY_GLOBAL_IDS = "globalIds";
  private JsonNullable<Set<Long>> globalIds = JsonNullable.<Set<Long>>undefined();

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  private JsonNullable<DateTimeRangeSelectorModel> createdDate = JsonNullable.<DateTimeRangeSelectorModel>undefined();

  public static final String JSON_PROPERTY_CREATED_BY_IDS = "createdByIds";
  private JsonNullable<Set<UUID>> createdByIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_TYPES = "types";
  private JsonNullable<Set<ProjectTypeModel>> types = JsonNullable.<Set<ProjectTypeModel>>undefined();

  public ProjectsFilterModel() { 
  }

  public ProjectsFilterModel name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Specifies a project name to search for
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public ProjectsFilterModel isFavorite(@jakarta.annotation.Nullable Boolean isFavorite) {
    this.isFavorite = JsonNullable.<Boolean>of(isFavorite);
    return this;
  }

  /**
   * Specifies a project favorite status to search for
   * @return isFavorite
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsFavorite() {
        return isFavorite.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsFavorite_JsonNullable() {
    return isFavorite;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
  public void setIsFavorite_JsonNullable(JsonNullable<Boolean> isFavorite) {
    this.isFavorite = isFavorite;
  }

  public void setIsFavorite(@jakarta.annotation.Nullable Boolean isFavorite) {
    this.isFavorite = JsonNullable.<Boolean>of(isFavorite);
  }


  public ProjectsFilterModel isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
    return this;
  }

  /**
   * Specifies a project deleted status to search for
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsDeleted() {
        return isDeleted.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsDeleted_JsonNullable() {
    return isDeleted;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  public void setIsDeleted_JsonNullable(JsonNullable<Boolean> isDeleted) {
    this.isDeleted = isDeleted;
  }

  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
  }


  public ProjectsFilterModel testCasesCount(@jakarta.annotation.Nullable Int32RangeSelectorModel testCasesCount) {
    this.testCasesCount = JsonNullable.<Int32RangeSelectorModel>of(testCasesCount);
    return this;
  }

  /**
   * Specifies a project range of test cases count to search for
   * @return testCasesCount
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Int32RangeSelectorModel getTestCasesCount() {
        return testCasesCount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEST_CASES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Int32RangeSelectorModel> getTestCasesCount_JsonNullable() {
    return testCasesCount;
  }
  
  @JsonProperty(JSON_PROPERTY_TEST_CASES_COUNT)
  public void setTestCasesCount_JsonNullable(JsonNullable<Int32RangeSelectorModel> testCasesCount) {
    this.testCasesCount = testCasesCount;
  }

  public void setTestCasesCount(@jakarta.annotation.Nullable Int32RangeSelectorModel testCasesCount) {
    this.testCasesCount = JsonNullable.<Int32RangeSelectorModel>of(testCasesCount);
  }


  public ProjectsFilterModel checklistsCount(@jakarta.annotation.Nullable Int32RangeSelectorModel checklistsCount) {
    this.checklistsCount = JsonNullable.<Int32RangeSelectorModel>of(checklistsCount);
    return this;
  }

  /**
   * Specifies a project range of checklists count to search for
   * @return checklistsCount
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Int32RangeSelectorModel getChecklistsCount() {
        return checklistsCount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHECKLISTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Int32RangeSelectorModel> getChecklistsCount_JsonNullable() {
    return checklistsCount;
  }
  
  @JsonProperty(JSON_PROPERTY_CHECKLISTS_COUNT)
  public void setChecklistsCount_JsonNullable(JsonNullable<Int32RangeSelectorModel> checklistsCount) {
    this.checklistsCount = checklistsCount;
  }

  public void setChecklistsCount(@jakarta.annotation.Nullable Int32RangeSelectorModel checklistsCount) {
    this.checklistsCount = JsonNullable.<Int32RangeSelectorModel>of(checklistsCount);
  }


  public ProjectsFilterModel sharedStepsCount(@jakarta.annotation.Nullable Int32RangeSelectorModel sharedStepsCount) {
    this.sharedStepsCount = JsonNullable.<Int32RangeSelectorModel>of(sharedStepsCount);
    return this;
  }

  /**
   * Specifies a project range of shared steps count to search for
   * @return sharedStepsCount
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Int32RangeSelectorModel getSharedStepsCount() {
        return sharedStepsCount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SHARED_STEPS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Int32RangeSelectorModel> getSharedStepsCount_JsonNullable() {
    return sharedStepsCount;
  }
  
  @JsonProperty(JSON_PROPERTY_SHARED_STEPS_COUNT)
  public void setSharedStepsCount_JsonNullable(JsonNullable<Int32RangeSelectorModel> sharedStepsCount) {
    this.sharedStepsCount = sharedStepsCount;
  }

  public void setSharedStepsCount(@jakarta.annotation.Nullable Int32RangeSelectorModel sharedStepsCount) {
    this.sharedStepsCount = JsonNullable.<Int32RangeSelectorModel>of(sharedStepsCount);
  }


  public ProjectsFilterModel autotestsCount(@jakarta.annotation.Nullable Int32RangeSelectorModel autotestsCount) {
    this.autotestsCount = JsonNullable.<Int32RangeSelectorModel>of(autotestsCount);
    return this;
  }

  /**
   * Specifies a project range of autotests count to search for
   * @return autotestsCount
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Int32RangeSelectorModel getAutotestsCount() {
        return autotestsCount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AUTOTESTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Int32RangeSelectorModel> getAutotestsCount_JsonNullable() {
    return autotestsCount;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTOTESTS_COUNT)
  public void setAutotestsCount_JsonNullable(JsonNullable<Int32RangeSelectorModel> autotestsCount) {
    this.autotestsCount = autotestsCount;
  }

  public void setAutotestsCount(@jakarta.annotation.Nullable Int32RangeSelectorModel autotestsCount) {
    this.autotestsCount = JsonNullable.<Int32RangeSelectorModel>of(autotestsCount);
  }


  public ProjectsFilterModel globalIds(@jakarta.annotation.Nullable Set<Long> globalIds) {
    this.globalIds = JsonNullable.<Set<Long>>of(globalIds);
    return this;
  }

  public ProjectsFilterModel addGlobalIdsItem(Long globalIdsItem) {
    if (this.globalIds == null || !this.globalIds.isPresent()) {
      this.globalIds = JsonNullable.<Set<Long>>of(new LinkedHashSet<>());
    }
    try {
      this.globalIds.get().add(globalIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies a project global IDs to search for
   * @return globalIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<Long> getGlobalIds() {
        return globalIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GLOBAL_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<Long>> getGlobalIds_JsonNullable() {
    return globalIds;
  }
  
  @JsonProperty(JSON_PROPERTY_GLOBAL_IDS)
  public void setGlobalIds_JsonNullable(JsonNullable<Set<Long>> globalIds) {
    this.globalIds = globalIds;
  }

  public void setGlobalIds(@jakarta.annotation.Nullable Set<Long> globalIds) {
    this.globalIds = JsonNullable.<Set<Long>>of(globalIds);
  }


  public ProjectsFilterModel createdDate(@jakarta.annotation.Nullable DateTimeRangeSelectorModel createdDate) {
    this.createdDate = JsonNullable.<DateTimeRangeSelectorModel>of(createdDate);
    return this;
  }

  /**
   * Specifies a project range of creation date to search for
   * @return createdDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public DateTimeRangeSelectorModel getCreatedDate() {
        return createdDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DateTimeRangeSelectorModel> getCreatedDate_JsonNullable() {
    return createdDate;
  }
  
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  public void setCreatedDate_JsonNullable(JsonNullable<DateTimeRangeSelectorModel> createdDate) {
    this.createdDate = createdDate;
  }

  public void setCreatedDate(@jakarta.annotation.Nullable DateTimeRangeSelectorModel createdDate) {
    this.createdDate = JsonNullable.<DateTimeRangeSelectorModel>of(createdDate);
  }


  public ProjectsFilterModel createdByIds(@jakarta.annotation.Nullable Set<UUID> createdByIds) {
    this.createdByIds = JsonNullable.<Set<UUID>>of(createdByIds);
    return this;
  }

  public ProjectsFilterModel addCreatedByIdsItem(UUID createdByIdsItem) {
    if (this.createdByIds == null || !this.createdByIds.isPresent()) {
      this.createdByIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.createdByIds.get().add(createdByIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies an autotest creator IDs to search for
   * @return createdByIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getCreatedByIds() {
        return createdByIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CREATED_BY_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getCreatedByIds_JsonNullable() {
    return createdByIds;
  }
  
  @JsonProperty(JSON_PROPERTY_CREATED_BY_IDS)
  public void setCreatedByIds_JsonNullable(JsonNullable<Set<UUID>> createdByIds) {
    this.createdByIds = createdByIds;
  }

  public void setCreatedByIds(@jakarta.annotation.Nullable Set<UUID> createdByIds) {
    this.createdByIds = JsonNullable.<Set<UUID>>of(createdByIds);
  }


  public ProjectsFilterModel types(@jakarta.annotation.Nullable Set<ProjectTypeModel> types) {
    this.types = JsonNullable.<Set<ProjectTypeModel>>of(types);
    return this;
  }

  public ProjectsFilterModel addTypesItem(ProjectTypeModel typesItem) {
    if (this.types == null || !this.types.isPresent()) {
      this.types = JsonNullable.<Set<ProjectTypeModel>>of(new LinkedHashSet<>());
    }
    try {
      this.types.get().add(typesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of project types to search for
   * @return types
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<ProjectTypeModel> getTypes() {
        return types.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<ProjectTypeModel>> getTypes_JsonNullable() {
    return types;
  }
  
  @JsonProperty(JSON_PROPERTY_TYPES)
  public void setTypes_JsonNullable(JsonNullable<Set<ProjectTypeModel>> types) {
    this.types = types;
  }

  public void setTypes(@jakarta.annotation.Nullable Set<ProjectTypeModel> types) {
    this.types = JsonNullable.<Set<ProjectTypeModel>>of(types);
  }


  /**
   * Return true if this ProjectsFilterModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectsFilterModel projectsFilterModel = (ProjectsFilterModel) o;
    return equalsNullable(this.name, projectsFilterModel.name) &&
        equalsNullable(this.isFavorite, projectsFilterModel.isFavorite) &&
        equalsNullable(this.isDeleted, projectsFilterModel.isDeleted) &&
        equalsNullable(this.testCasesCount, projectsFilterModel.testCasesCount) &&
        equalsNullable(this.checklistsCount, projectsFilterModel.checklistsCount) &&
        equalsNullable(this.sharedStepsCount, projectsFilterModel.sharedStepsCount) &&
        equalsNullable(this.autotestsCount, projectsFilterModel.autotestsCount) &&
        equalsNullable(this.globalIds, projectsFilterModel.globalIds) &&
        equalsNullable(this.createdDate, projectsFilterModel.createdDate) &&
        equalsNullable(this.createdByIds, projectsFilterModel.createdByIds) &&
        equalsNullable(this.types, projectsFilterModel.types);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(name), hashCodeNullable(isFavorite), hashCodeNullable(isDeleted), hashCodeNullable(testCasesCount), hashCodeNullable(checklistsCount), hashCodeNullable(sharedStepsCount), hashCodeNullable(autotestsCount), hashCodeNullable(globalIds), hashCodeNullable(createdDate), hashCodeNullable(createdByIds), hashCodeNullable(types));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectsFilterModel {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isFavorite: ").append(toIndentedString(isFavorite)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    testCasesCount: ").append(toIndentedString(testCasesCount)).append("\n");
    sb.append("    checklistsCount: ").append(toIndentedString(checklistsCount)).append("\n");
    sb.append("    sharedStepsCount: ").append(toIndentedString(sharedStepsCount)).append("\n");
    sb.append("    autotestsCount: ").append(toIndentedString(autotestsCount)).append("\n");
    sb.append("    globalIds: ").append(toIndentedString(globalIds)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    createdByIds: ").append(toIndentedString(createdByIds)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

