/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * SharedStepResultApiModel
 */
@JsonPropertyOrder({
  SharedStepResultApiModel.JSON_PROPERTY_STEP_ID,
  SharedStepResultApiModel.JSON_PROPERTY_OUTCOME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SharedStepResultApiModel {
  public static final String JSON_PROPERTY_STEP_ID = "stepId";
  @jakarta.annotation.Nonnull
  private UUID stepId;

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @jakarta.annotation.Nonnull
  private String outcome;

  public SharedStepResultApiModel() { 
  }

  public SharedStepResultApiModel stepId(@jakarta.annotation.Nonnull UUID stepId) {
    this.stepId = stepId;
    return this;
  }

  /**
   * Get stepId
   * @return stepId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STEP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getStepId() {
    return stepId;
  }


  @JsonProperty(JSON_PROPERTY_STEP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStepId(@jakarta.annotation.Nonnull UUID stepId) {
    this.stepId = stepId;
  }


  public SharedStepResultApiModel outcome(@jakarta.annotation.Nonnull String outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOutcome() {
    return outcome;
  }


  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutcome(@jakarta.annotation.Nonnull String outcome) {
    this.outcome = outcome;
  }


  /**
   * Return true if this SharedStepResultApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SharedStepResultApiModel sharedStepResultApiModel = (SharedStepResultApiModel) o;
    return Objects.equals(this.stepId, sharedStepResultApiModel.stepId) &&
        Objects.equals(this.outcome, sharedStepResultApiModel.outcome);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stepId, outcome);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SharedStepResultApiModel {\n");
    sb.append("    stepId: ").append(toIndentedString(stepId)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

