/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * StepPostModel
 */
@JsonPropertyOrder({
  StepPostModel.JSON_PROPERTY_ACTION,
  StepPostModel.JSON_PROPERTY_EXPECTED,
  StepPostModel.JSON_PROPERTY_TEST_DATA,
  StepPostModel.JSON_PROPERTY_COMMENTS,
  StepPostModel.JSON_PROPERTY_WORK_ITEM_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class StepPostModel {
  public static final String JSON_PROPERTY_ACTION = "action";
  private JsonNullable<String> action = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXPECTED = "expected";
  private JsonNullable<String> expected = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TEST_DATA = "testData";
  private JsonNullable<String> testData = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  private JsonNullable<String> comments = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_WORK_ITEM_ID = "workItemId";
  private JsonNullable<UUID> workItemId = JsonNullable.<UUID>undefined();

  public StepPostModel() { 
  }

  public StepPostModel action(@jakarta.annotation.Nullable String action) {
    this.action = JsonNullable.<String>of(action);
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAction() {
        return action.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAction_JsonNullable() {
    return action;
  }
  
  @JsonProperty(JSON_PROPERTY_ACTION)
  public void setAction_JsonNullable(JsonNullable<String> action) {
    this.action = action;
  }

  public void setAction(@jakarta.annotation.Nullable String action) {
    this.action = JsonNullable.<String>of(action);
  }


  public StepPostModel expected(@jakarta.annotation.Nullable String expected) {
    this.expected = JsonNullable.<String>of(expected);
    return this;
  }

  /**
   * Get expected
   * @return expected
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getExpected() {
        return expected.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXPECTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExpected_JsonNullable() {
    return expected;
  }
  
  @JsonProperty(JSON_PROPERTY_EXPECTED)
  public void setExpected_JsonNullable(JsonNullable<String> expected) {
    this.expected = expected;
  }

  public void setExpected(@jakarta.annotation.Nullable String expected) {
    this.expected = JsonNullable.<String>of(expected);
  }


  public StepPostModel testData(@jakarta.annotation.Nullable String testData) {
    this.testData = JsonNullable.<String>of(testData);
    return this;
  }

  /**
   * Get testData
   * @return testData
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTestData() {
        return testData.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEST_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTestData_JsonNullable() {
    return testData;
  }
  
  @JsonProperty(JSON_PROPERTY_TEST_DATA)
  public void setTestData_JsonNullable(JsonNullable<String> testData) {
    this.testData = testData;
  }

  public void setTestData(@jakarta.annotation.Nullable String testData) {
    this.testData = JsonNullable.<String>of(testData);
  }


  public StepPostModel comments(@jakarta.annotation.Nullable String comments) {
    this.comments = JsonNullable.<String>of(comments);
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getComments() {
        return comments.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getComments_JsonNullable() {
    return comments;
  }
  
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  public void setComments_JsonNullable(JsonNullable<String> comments) {
    this.comments = comments;
  }

  public void setComments(@jakarta.annotation.Nullable String comments) {
    this.comments = JsonNullable.<String>of(comments);
  }


  public StepPostModel workItemId(@jakarta.annotation.Nullable UUID workItemId) {
    this.workItemId = JsonNullable.<UUID>of(workItemId);
    return this;
  }

  /**
   * Get workItemId
   * @return workItemId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public UUID getWorkItemId() {
        return workItemId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WORK_ITEM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getWorkItemId_JsonNullable() {
    return workItemId;
  }
  
  @JsonProperty(JSON_PROPERTY_WORK_ITEM_ID)
  public void setWorkItemId_JsonNullable(JsonNullable<UUID> workItemId) {
    this.workItemId = workItemId;
  }

  public void setWorkItemId(@jakarta.annotation.Nullable UUID workItemId) {
    this.workItemId = JsonNullable.<UUID>of(workItemId);
  }


  /**
   * Return true if this StepPostModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StepPostModel stepPostModel = (StepPostModel) o;
    return equalsNullable(this.action, stepPostModel.action) &&
        equalsNullable(this.expected, stepPostModel.expected) &&
        equalsNullable(this.testData, stepPostModel.testData) &&
        equalsNullable(this.comments, stepPostModel.comments) &&
        equalsNullable(this.workItemId, stepPostModel.workItemId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(action), hashCodeNullable(expected), hashCodeNullable(testData), hashCodeNullable(comments), hashCodeNullable(workItemId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StepPostModel {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    expected: ").append(toIndentedString(expected)).append("\n");
    sb.append("    testData: ").append(toIndentedString(testData)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    workItemId: ").append(toIndentedString(workItemId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

