/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.SharedStepResultApiModel;
import ru.testit.adaptersapi.model.StepCommentApiModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * StepResultApiModel
 */
@JsonPropertyOrder({
  StepResultApiModel.JSON_PROPERTY_STEP_ID,
  StepResultApiModel.JSON_PROPERTY_OUTCOME,
  StepResultApiModel.JSON_PROPERTY_SHARED_STEP_VERSION_ID,
  StepResultApiModel.JSON_PROPERTY_SHARED_STEP_RESULTS,
  StepResultApiModel.JSON_PROPERTY_COMMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class StepResultApiModel {
  public static final String JSON_PROPERTY_STEP_ID = "stepId";
  @jakarta.annotation.Nonnull
  private UUID stepId;

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @jakarta.annotation.Nonnull
  private String outcome;

  public static final String JSON_PROPERTY_SHARED_STEP_VERSION_ID = "sharedStepVersionId";
  private JsonNullable<UUID> sharedStepVersionId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_SHARED_STEP_RESULTS = "sharedStepResults";
  private JsonNullable<List<SharedStepResultApiModel>> sharedStepResults = JsonNullable.<List<SharedStepResultApiModel>>undefined();

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private JsonNullable<StepCommentApiModel> comment = JsonNullable.<StepCommentApiModel>undefined();

  public StepResultApiModel() { 
  }

  public StepResultApiModel stepId(@jakarta.annotation.Nonnull UUID stepId) {
    this.stepId = stepId;
    return this;
  }

  /**
   * Get stepId
   * @return stepId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STEP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getStepId() {
    return stepId;
  }


  @JsonProperty(JSON_PROPERTY_STEP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStepId(@jakarta.annotation.Nonnull UUID stepId) {
    this.stepId = stepId;
  }


  public StepResultApiModel outcome(@jakarta.annotation.Nonnull String outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOutcome() {
    return outcome;
  }


  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutcome(@jakarta.annotation.Nonnull String outcome) {
    this.outcome = outcome;
  }


  public StepResultApiModel sharedStepVersionId(@jakarta.annotation.Nullable UUID sharedStepVersionId) {
    this.sharedStepVersionId = JsonNullable.<UUID>of(sharedStepVersionId);
    return this;
  }

  /**
   * Get sharedStepVersionId
   * @return sharedStepVersionId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public UUID getSharedStepVersionId() {
        return sharedStepVersionId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SHARED_STEP_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getSharedStepVersionId_JsonNullable() {
    return sharedStepVersionId;
  }
  
  @JsonProperty(JSON_PROPERTY_SHARED_STEP_VERSION_ID)
  public void setSharedStepVersionId_JsonNullable(JsonNullable<UUID> sharedStepVersionId) {
    this.sharedStepVersionId = sharedStepVersionId;
  }

  public void setSharedStepVersionId(@jakarta.annotation.Nullable UUID sharedStepVersionId) {
    this.sharedStepVersionId = JsonNullable.<UUID>of(sharedStepVersionId);
  }


  public StepResultApiModel sharedStepResults(@jakarta.annotation.Nullable List<SharedStepResultApiModel> sharedStepResults) {
    this.sharedStepResults = JsonNullable.<List<SharedStepResultApiModel>>of(sharedStepResults);
    return this;
  }

  public StepResultApiModel addSharedStepResultsItem(SharedStepResultApiModel sharedStepResultsItem) {
    if (this.sharedStepResults == null || !this.sharedStepResults.isPresent()) {
      this.sharedStepResults = JsonNullable.<List<SharedStepResultApiModel>>of(new ArrayList<>());
    }
    try {
      this.sharedStepResults.get().add(sharedStepResultsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get sharedStepResults
   * @return sharedStepResults
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<SharedStepResultApiModel> getSharedStepResults() {
        return sharedStepResults.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SHARED_STEP_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<SharedStepResultApiModel>> getSharedStepResults_JsonNullable() {
    return sharedStepResults;
  }
  
  @JsonProperty(JSON_PROPERTY_SHARED_STEP_RESULTS)
  public void setSharedStepResults_JsonNullable(JsonNullable<List<SharedStepResultApiModel>> sharedStepResults) {
    this.sharedStepResults = sharedStepResults;
  }

  public void setSharedStepResults(@jakarta.annotation.Nullable List<SharedStepResultApiModel> sharedStepResults) {
    this.sharedStepResults = JsonNullable.<List<SharedStepResultApiModel>>of(sharedStepResults);
  }


  public StepResultApiModel comment(@jakarta.annotation.Nullable StepCommentApiModel comment) {
    this.comment = JsonNullable.<StepCommentApiModel>of(comment);
    return this;
  }

  /**
   * Get comment
   * @return comment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public StepCommentApiModel getComment() {
        return comment.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<StepCommentApiModel> getComment_JsonNullable() {
    return comment;
  }
  
  @JsonProperty(JSON_PROPERTY_COMMENT)
  public void setComment_JsonNullable(JsonNullable<StepCommentApiModel> comment) {
    this.comment = comment;
  }

  public void setComment(@jakarta.annotation.Nullable StepCommentApiModel comment) {
    this.comment = JsonNullable.<StepCommentApiModel>of(comment);
  }


  /**
   * Return true if this StepResultApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StepResultApiModel stepResultApiModel = (StepResultApiModel) o;
    return Objects.equals(this.stepId, stepResultApiModel.stepId) &&
        Objects.equals(this.outcome, stepResultApiModel.outcome) &&
        equalsNullable(this.sharedStepVersionId, stepResultApiModel.sharedStepVersionId) &&
        equalsNullable(this.sharedStepResults, stepResultApiModel.sharedStepResults) &&
        equalsNullable(this.comment, stepResultApiModel.comment);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(stepId, outcome, hashCodeNullable(sharedStepVersionId), hashCodeNullable(sharedStepResults), hashCodeNullable(comment));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StepResultApiModel {\n");
    sb.append("    stepId: ").append(toIndentedString(stepId)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    sharedStepVersionId: ").append(toIndentedString(sharedStepVersionId)).append("\n");
    sb.append("    sharedStepResults: ").append(toIndentedString(sharedStepResults)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

