/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.AttachmentApiResult;
import ru.testit.adaptersapi.model.AutoTest;
import ru.testit.adaptersapi.model.AutoTestStepResult;
import ru.testit.adaptersapi.model.LinkApiResult;
import ru.testit.adaptersapi.model.StepCommentApiModel;
import ru.testit.adaptersapi.model.StepResultApiModel;
import ru.testit.adaptersapi.model.TestResultOutcome;
import ru.testit.adaptersapi.model.TestStatusApiResult;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * TestResultResponse
 */
@JsonPropertyOrder({
  TestResultResponse.JSON_PROPERTY_ID,
  TestResultResponse.JSON_PROPERTY_FAILURE_CLASS_IDS,
  TestResultResponse.JSON_PROPERTY_CONFIGURATION_ID,
  TestResultResponse.JSON_PROPERTY_TEST_POINT_ID,
  TestResultResponse.JSON_PROPERTY_TEST_RUN_ID,
  TestResultResponse.JSON_PROPERTY_STEP_COMMENTS,
  TestResultResponse.JSON_PROPERTY_OUTCOME,
  TestResultResponse.JSON_PROPERTY_STATUS,
  TestResultResponse.JSON_PROPERTY_COMMENT,
  TestResultResponse.JSON_PROPERTY_LINKS,
  TestResultResponse.JSON_PROPERTY_STEP_RESULTS,
  TestResultResponse.JSON_PROPERTY_ATTACHMENTS,
  TestResultResponse.JSON_PROPERTY_AUTO_TEST_ID,
  TestResultResponse.JSON_PROPERTY_DURATION_IN_MS,
  TestResultResponse.JSON_PROPERTY_TRACES,
  TestResultResponse.JSON_PROPERTY_FAILURE_TYPE,
  TestResultResponse.JSON_PROPERTY_MESSAGE,
  TestResultResponse.JSON_PROPERTY_AUTO_TEST,
  TestResultResponse.JSON_PROPERTY_AUTO_TEST_STEP_RESULTS,
  TestResultResponse.JSON_PROPERTY_SETUP_RESULTS,
  TestResultResponse.JSON_PROPERTY_TEARDOWN_RESULTS,
  TestResultResponse.JSON_PROPERTY_PARAMETERS,
  TestResultResponse.JSON_PROPERTY_PROPERTIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class TestResultResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_FAILURE_CLASS_IDS = "failureClassIds";
  @jakarta.annotation.Nonnull
  private List<UUID> failureClassIds = new ArrayList<>();

  public static final String JSON_PROPERTY_CONFIGURATION_ID = "configurationId";
  @jakarta.annotation.Nonnull
  private UUID configurationId;

  public static final String JSON_PROPERTY_TEST_POINT_ID = "testPointId";
  @jakarta.annotation.Nonnull
  private UUID testPointId;

  public static final String JSON_PROPERTY_TEST_RUN_ID = "testRunId";
  @jakarta.annotation.Nonnull
  private UUID testRunId;

  public static final String JSON_PROPERTY_STEP_COMMENTS = "stepComments";
  private JsonNullable<List<StepCommentApiModel>> stepComments = JsonNullable.<List<StepCommentApiModel>>undefined();

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @Deprecated
  private JsonNullable<TestResultOutcome> outcome = JsonNullable.<TestResultOutcome>undefined();

  public static final String JSON_PROPERTY_STATUS = "status";
  private JsonNullable<TestStatusApiResult> status = JsonNullable.<TestStatusApiResult>undefined();

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private JsonNullable<String> comment = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LINKS = "links";
  private JsonNullable<List<LinkApiResult>> links = JsonNullable.<List<LinkApiResult>>undefined();

  public static final String JSON_PROPERTY_STEP_RESULTS = "stepResults";
  private JsonNullable<List<StepResultApiModel>> stepResults = JsonNullable.<List<StepResultApiModel>>undefined();

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  private JsonNullable<List<AttachmentApiResult>> attachments = JsonNullable.<List<AttachmentApiResult>>undefined();

  public static final String JSON_PROPERTY_AUTO_TEST_ID = "autoTestId";
  private JsonNullable<UUID> autoTestId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_DURATION_IN_MS = "durationInMs";
  private JsonNullable<Long> durationInMs = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_TRACES = "traces";
  private JsonNullable<String> traces = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FAILURE_TYPE = "failureType";
  private JsonNullable<String> failureType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private JsonNullable<String> message = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AUTO_TEST = "autoTest";
  private JsonNullable<AutoTest> autoTest = JsonNullable.<AutoTest>undefined();

  public static final String JSON_PROPERTY_AUTO_TEST_STEP_RESULTS = "autoTestStepResults";
  private JsonNullable<List<AutoTestStepResult>> autoTestStepResults = JsonNullable.<List<AutoTestStepResult>>undefined();

  public static final String JSON_PROPERTY_SETUP_RESULTS = "setupResults";
  private JsonNullable<List<AutoTestStepResult>> setupResults = JsonNullable.<List<AutoTestStepResult>>undefined();

  public static final String JSON_PROPERTY_TEARDOWN_RESULTS = "teardownResults";
  private JsonNullable<List<AutoTestStepResult>> teardownResults = JsonNullable.<List<AutoTestStepResult>>undefined();

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  private JsonNullable<Map<String, String>> parameters = JsonNullable.<Map<String, String>>undefined();

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  private JsonNullable<Map<String, String>> properties = JsonNullable.<Map<String, String>>undefined();

  public TestResultResponse() { 
  }

  public TestResultResponse id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public TestResultResponse failureClassIds(@jakarta.annotation.Nonnull List<UUID> failureClassIds) {
    this.failureClassIds = failureClassIds;
    return this;
  }

  public TestResultResponse addFailureClassIdsItem(UUID failureClassIdsItem) {
    if (this.failureClassIds == null) {
      this.failureClassIds = new ArrayList<>();
    }
    this.failureClassIds.add(failureClassIdsItem);
    return this;
  }

  /**
   * Get failureClassIds
   * @return failureClassIds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FAILURE_CLASS_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<UUID> getFailureClassIds() {
    return failureClassIds;
  }


  @JsonProperty(JSON_PROPERTY_FAILURE_CLASS_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFailureClassIds(@jakarta.annotation.Nonnull List<UUID> failureClassIds) {
    this.failureClassIds = failureClassIds;
  }


  public TestResultResponse configurationId(@jakarta.annotation.Nonnull UUID configurationId) {
    this.configurationId = configurationId;
    return this;
  }

  /**
   * Get configurationId
   * @return configurationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONFIGURATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getConfigurationId() {
    return configurationId;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfigurationId(@jakarta.annotation.Nonnull UUID configurationId) {
    this.configurationId = configurationId;
  }


  public TestResultResponse testPointId(@jakarta.annotation.Nonnull UUID testPointId) {
    this.testPointId = testPointId;
    return this;
  }

  /**
   * Get testPointId
   * @return testPointId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEST_POINT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getTestPointId() {
    return testPointId;
  }


  @JsonProperty(JSON_PROPERTY_TEST_POINT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTestPointId(@jakarta.annotation.Nonnull UUID testPointId) {
    this.testPointId = testPointId;
  }


  public TestResultResponse testRunId(@jakarta.annotation.Nonnull UUID testRunId) {
    this.testRunId = testRunId;
    return this;
  }

  /**
   * Get testRunId
   * @return testRunId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEST_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getTestRunId() {
    return testRunId;
  }


  @JsonProperty(JSON_PROPERTY_TEST_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTestRunId(@jakarta.annotation.Nonnull UUID testRunId) {
    this.testRunId = testRunId;
  }


  public TestResultResponse stepComments(@jakarta.annotation.Nullable List<StepCommentApiModel> stepComments) {
    this.stepComments = JsonNullable.<List<StepCommentApiModel>>of(stepComments);
    return this;
  }

  public TestResultResponse addStepCommentsItem(StepCommentApiModel stepCommentsItem) {
    if (this.stepComments == null || !this.stepComments.isPresent()) {
      this.stepComments = JsonNullable.<List<StepCommentApiModel>>of(new ArrayList<>());
    }
    try {
      this.stepComments.get().add(stepCommentsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get stepComments
   * @return stepComments
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<StepCommentApiModel> getStepComments() {
        return stepComments.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STEP_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<StepCommentApiModel>> getStepComments_JsonNullable() {
    return stepComments;
  }
  
  @JsonProperty(JSON_PROPERTY_STEP_COMMENTS)
  public void setStepComments_JsonNullable(JsonNullable<List<StepCommentApiModel>> stepComments) {
    this.stepComments = stepComments;
  }

  public void setStepComments(@jakarta.annotation.Nullable List<StepCommentApiModel> stepComments) {
    this.stepComments = JsonNullable.<List<StepCommentApiModel>>of(stepComments);
  }


  @Deprecated
  public TestResultResponse outcome(@jakarta.annotation.Nullable TestResultOutcome outcome) {
    this.outcome = JsonNullable.<TestResultOutcome>of(outcome);
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable
  @JsonIgnore

  public TestResultOutcome getOutcome() {
        return outcome.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<TestResultOutcome> getOutcome_JsonNullable() {
    return outcome;
  }
  
  @JsonProperty(JSON_PROPERTY_OUTCOME)
  public void setOutcome_JsonNullable(JsonNullable<TestResultOutcome> outcome) {
    this.outcome = outcome;
  }

  @Deprecated
  public void setOutcome(@jakarta.annotation.Nullable TestResultOutcome outcome) {
    this.outcome = JsonNullable.<TestResultOutcome>of(outcome);
  }


  public TestResultResponse status(@jakarta.annotation.Nullable TestStatusApiResult status) {
    this.status = JsonNullable.<TestStatusApiResult>of(status);
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public TestStatusApiResult getStatus() {
        return status.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<TestStatusApiResult> getStatus_JsonNullable() {
    return status;
  }
  
  @JsonProperty(JSON_PROPERTY_STATUS)
  public void setStatus_JsonNullable(JsonNullable<TestStatusApiResult> status) {
    this.status = status;
  }

  public void setStatus(@jakarta.annotation.Nullable TestStatusApiResult status) {
    this.status = JsonNullable.<TestStatusApiResult>of(status);
  }


  public TestResultResponse comment(@jakarta.annotation.Nullable String comment) {
    this.comment = JsonNullable.<String>of(comment);
    return this;
  }

  /**
   * Get comment
   * @return comment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getComment() {
        return comment.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getComment_JsonNullable() {
    return comment;
  }
  
  @JsonProperty(JSON_PROPERTY_COMMENT)
  public void setComment_JsonNullable(JsonNullable<String> comment) {
    this.comment = comment;
  }

  public void setComment(@jakarta.annotation.Nullable String comment) {
    this.comment = JsonNullable.<String>of(comment);
  }


  public TestResultResponse links(@jakarta.annotation.Nullable List<LinkApiResult> links) {
    this.links = JsonNullable.<List<LinkApiResult>>of(links);
    return this;
  }

  public TestResultResponse addLinksItem(LinkApiResult linksItem) {
    if (this.links == null || !this.links.isPresent()) {
      this.links = JsonNullable.<List<LinkApiResult>>of(new ArrayList<>());
    }
    try {
      this.links.get().add(linksItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<LinkApiResult> getLinks() {
        return links.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<LinkApiResult>> getLinks_JsonNullable() {
    return links;
  }
  
  @JsonProperty(JSON_PROPERTY_LINKS)
  public void setLinks_JsonNullable(JsonNullable<List<LinkApiResult>> links) {
    this.links = links;
  }

  public void setLinks(@jakarta.annotation.Nullable List<LinkApiResult> links) {
    this.links = JsonNullable.<List<LinkApiResult>>of(links);
  }


  public TestResultResponse stepResults(@jakarta.annotation.Nullable List<StepResultApiModel> stepResults) {
    this.stepResults = JsonNullable.<List<StepResultApiModel>>of(stepResults);
    return this;
  }

  public TestResultResponse addStepResultsItem(StepResultApiModel stepResultsItem) {
    if (this.stepResults == null || !this.stepResults.isPresent()) {
      this.stepResults = JsonNullable.<List<StepResultApiModel>>of(new ArrayList<>());
    }
    try {
      this.stepResults.get().add(stepResultsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get stepResults
   * @return stepResults
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<StepResultApiModel> getStepResults() {
        return stepResults.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STEP_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<StepResultApiModel>> getStepResults_JsonNullable() {
    return stepResults;
  }
  
  @JsonProperty(JSON_PROPERTY_STEP_RESULTS)
  public void setStepResults_JsonNullable(JsonNullable<List<StepResultApiModel>> stepResults) {
    this.stepResults = stepResults;
  }

  public void setStepResults(@jakarta.annotation.Nullable List<StepResultApiModel> stepResults) {
    this.stepResults = JsonNullable.<List<StepResultApiModel>>of(stepResults);
  }


  public TestResultResponse attachments(@jakarta.annotation.Nullable List<AttachmentApiResult> attachments) {
    this.attachments = JsonNullable.<List<AttachmentApiResult>>of(attachments);
    return this;
  }

  public TestResultResponse addAttachmentsItem(AttachmentApiResult attachmentsItem) {
    if (this.attachments == null || !this.attachments.isPresent()) {
      this.attachments = JsonNullable.<List<AttachmentApiResult>>of(new ArrayList<>());
    }
    try {
      this.attachments.get().add(attachmentsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get attachments
   * @return attachments
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AttachmentApiResult> getAttachments() {
        return attachments.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AttachmentApiResult>> getAttachments_JsonNullable() {
    return attachments;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  public void setAttachments_JsonNullable(JsonNullable<List<AttachmentApiResult>> attachments) {
    this.attachments = attachments;
  }

  public void setAttachments(@jakarta.annotation.Nullable List<AttachmentApiResult> attachments) {
    this.attachments = JsonNullable.<List<AttachmentApiResult>>of(attachments);
  }


  public TestResultResponse autoTestId(@jakarta.annotation.Nullable UUID autoTestId) {
    this.autoTestId = JsonNullable.<UUID>of(autoTestId);
    return this;
  }

  /**
   * Get autoTestId
   * @return autoTestId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public UUID getAutoTestId() {
        return autoTestId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AUTO_TEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getAutoTestId_JsonNullable() {
    return autoTestId;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTO_TEST_ID)
  public void setAutoTestId_JsonNullable(JsonNullable<UUID> autoTestId) {
    this.autoTestId = autoTestId;
  }

  public void setAutoTestId(@jakarta.annotation.Nullable UUID autoTestId) {
    this.autoTestId = JsonNullable.<UUID>of(autoTestId);
  }


  public TestResultResponse durationInMs(@jakarta.annotation.Nullable Long durationInMs) {
    this.durationInMs = JsonNullable.<Long>of(durationInMs);
    return this;
  }

  /**
   * Get durationInMs
   * @return durationInMs
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getDurationInMs() {
        return durationInMs.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DURATION_IN_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getDurationInMs_JsonNullable() {
    return durationInMs;
  }
  
  @JsonProperty(JSON_PROPERTY_DURATION_IN_MS)
  public void setDurationInMs_JsonNullable(JsonNullable<Long> durationInMs) {
    this.durationInMs = durationInMs;
  }

  public void setDurationInMs(@jakarta.annotation.Nullable Long durationInMs) {
    this.durationInMs = JsonNullable.<Long>of(durationInMs);
  }


  public TestResultResponse traces(@jakarta.annotation.Nullable String traces) {
    this.traces = JsonNullable.<String>of(traces);
    return this;
  }

  /**
   * Get traces
   * @return traces
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTraces() {
        return traces.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTraces_JsonNullable() {
    return traces;
  }
  
  @JsonProperty(JSON_PROPERTY_TRACES)
  public void setTraces_JsonNullable(JsonNullable<String> traces) {
    this.traces = traces;
  }

  public void setTraces(@jakarta.annotation.Nullable String traces) {
    this.traces = JsonNullable.<String>of(traces);
  }


  public TestResultResponse failureType(@jakarta.annotation.Nullable String failureType) {
    this.failureType = JsonNullable.<String>of(failureType);
    return this;
  }

  /**
   * Get failureType
   * @return failureType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getFailureType() {
        return failureType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FAILURE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFailureType_JsonNullable() {
    return failureType;
  }
  
  @JsonProperty(JSON_PROPERTY_FAILURE_TYPE)
  public void setFailureType_JsonNullable(JsonNullable<String> failureType) {
    this.failureType = failureType;
  }

  public void setFailureType(@jakarta.annotation.Nullable String failureType) {
    this.failureType = JsonNullable.<String>of(failureType);
  }


  public TestResultResponse message(@jakarta.annotation.Nullable String message) {
    this.message = JsonNullable.<String>of(message);
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getMessage() {
        return message.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMessage_JsonNullable() {
    return message;
  }
  
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  public void setMessage_JsonNullable(JsonNullable<String> message) {
    this.message = message;
  }

  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = JsonNullable.<String>of(message);
  }


  public TestResultResponse autoTest(@jakarta.annotation.Nullable AutoTest autoTest) {
    this.autoTest = JsonNullable.<AutoTest>of(autoTest);
    return this;
  }

  /**
   * Get autoTest
   * @return autoTest
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public AutoTest getAutoTest() {
        return autoTest.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AUTO_TEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<AutoTest> getAutoTest_JsonNullable() {
    return autoTest;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTO_TEST)
  public void setAutoTest_JsonNullable(JsonNullable<AutoTest> autoTest) {
    this.autoTest = autoTest;
  }

  public void setAutoTest(@jakarta.annotation.Nullable AutoTest autoTest) {
    this.autoTest = JsonNullable.<AutoTest>of(autoTest);
  }


  public TestResultResponse autoTestStepResults(@jakarta.annotation.Nullable List<AutoTestStepResult> autoTestStepResults) {
    this.autoTestStepResults = JsonNullable.<List<AutoTestStepResult>>of(autoTestStepResults);
    return this;
  }

  public TestResultResponse addAutoTestStepResultsItem(AutoTestStepResult autoTestStepResultsItem) {
    if (this.autoTestStepResults == null || !this.autoTestStepResults.isPresent()) {
      this.autoTestStepResults = JsonNullable.<List<AutoTestStepResult>>of(new ArrayList<>());
    }
    try {
      this.autoTestStepResults.get().add(autoTestStepResultsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get autoTestStepResults
   * @return autoTestStepResults
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AutoTestStepResult> getAutoTestStepResults() {
        return autoTestStepResults.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AUTO_TEST_STEP_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AutoTestStepResult>> getAutoTestStepResults_JsonNullable() {
    return autoTestStepResults;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTO_TEST_STEP_RESULTS)
  public void setAutoTestStepResults_JsonNullable(JsonNullable<List<AutoTestStepResult>> autoTestStepResults) {
    this.autoTestStepResults = autoTestStepResults;
  }

  public void setAutoTestStepResults(@jakarta.annotation.Nullable List<AutoTestStepResult> autoTestStepResults) {
    this.autoTestStepResults = JsonNullable.<List<AutoTestStepResult>>of(autoTestStepResults);
  }


  public TestResultResponse setupResults(@jakarta.annotation.Nullable List<AutoTestStepResult> setupResults) {
    this.setupResults = JsonNullable.<List<AutoTestStepResult>>of(setupResults);
    return this;
  }

  public TestResultResponse addSetupResultsItem(AutoTestStepResult setupResultsItem) {
    if (this.setupResults == null || !this.setupResults.isPresent()) {
      this.setupResults = JsonNullable.<List<AutoTestStepResult>>of(new ArrayList<>());
    }
    try {
      this.setupResults.get().add(setupResultsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get setupResults
   * @return setupResults
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AutoTestStepResult> getSetupResults() {
        return setupResults.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SETUP_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AutoTestStepResult>> getSetupResults_JsonNullable() {
    return setupResults;
  }
  
  @JsonProperty(JSON_PROPERTY_SETUP_RESULTS)
  public void setSetupResults_JsonNullable(JsonNullable<List<AutoTestStepResult>> setupResults) {
    this.setupResults = setupResults;
  }

  public void setSetupResults(@jakarta.annotation.Nullable List<AutoTestStepResult> setupResults) {
    this.setupResults = JsonNullable.<List<AutoTestStepResult>>of(setupResults);
  }


  public TestResultResponse teardownResults(@jakarta.annotation.Nullable List<AutoTestStepResult> teardownResults) {
    this.teardownResults = JsonNullable.<List<AutoTestStepResult>>of(teardownResults);
    return this;
  }

  public TestResultResponse addTeardownResultsItem(AutoTestStepResult teardownResultsItem) {
    if (this.teardownResults == null || !this.teardownResults.isPresent()) {
      this.teardownResults = JsonNullable.<List<AutoTestStepResult>>of(new ArrayList<>());
    }
    try {
      this.teardownResults.get().add(teardownResultsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get teardownResults
   * @return teardownResults
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AutoTestStepResult> getTeardownResults() {
        return teardownResults.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEARDOWN_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AutoTestStepResult>> getTeardownResults_JsonNullable() {
    return teardownResults;
  }
  
  @JsonProperty(JSON_PROPERTY_TEARDOWN_RESULTS)
  public void setTeardownResults_JsonNullable(JsonNullable<List<AutoTestStepResult>> teardownResults) {
    this.teardownResults = teardownResults;
  }

  public void setTeardownResults(@jakarta.annotation.Nullable List<AutoTestStepResult> teardownResults) {
    this.teardownResults = JsonNullable.<List<AutoTestStepResult>>of(teardownResults);
  }


  public TestResultResponse parameters(@jakarta.annotation.Nullable Map<String, String> parameters) {
    this.parameters = JsonNullable.<Map<String, String>>of(parameters);
    return this;
  }

  public TestResultResponse putParametersItem(String key, String parametersItem) {
    if (this.parameters == null || !this.parameters.isPresent()) {
      this.parameters = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.parameters.get().put(key, parametersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getParameters() {
        return parameters.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getParameters_JsonNullable() {
    return parameters;
  }
  
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  public void setParameters_JsonNullable(JsonNullable<Map<String, String>> parameters) {
    this.parameters = parameters;
  }

  public void setParameters(@jakarta.annotation.Nullable Map<String, String> parameters) {
    this.parameters = JsonNullable.<Map<String, String>>of(parameters);
  }


  public TestResultResponse properties(@jakarta.annotation.Nullable Map<String, String> properties) {
    this.properties = JsonNullable.<Map<String, String>>of(properties);
    return this;
  }

  public TestResultResponse putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null || !this.properties.isPresent()) {
      this.properties = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.properties.get().put(key, propertiesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getProperties() {
        return properties.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getProperties_JsonNullable() {
    return properties;
  }
  
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  public void setProperties_JsonNullable(JsonNullable<Map<String, String>> properties) {
    this.properties = properties;
  }

  public void setProperties(@jakarta.annotation.Nullable Map<String, String> properties) {
    this.properties = JsonNullable.<Map<String, String>>of(properties);
  }


  /**
   * Return true if this TestResultResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestResultResponse testResultResponse = (TestResultResponse) o;
    return Objects.equals(this.id, testResultResponse.id) &&
        Objects.equals(this.failureClassIds, testResultResponse.failureClassIds) &&
        Objects.equals(this.configurationId, testResultResponse.configurationId) &&
        Objects.equals(this.testPointId, testResultResponse.testPointId) &&
        Objects.equals(this.testRunId, testResultResponse.testRunId) &&
        equalsNullable(this.stepComments, testResultResponse.stepComments) &&
        equalsNullable(this.outcome, testResultResponse.outcome) &&
        equalsNullable(this.status, testResultResponse.status) &&
        equalsNullable(this.comment, testResultResponse.comment) &&
        equalsNullable(this.links, testResultResponse.links) &&
        equalsNullable(this.stepResults, testResultResponse.stepResults) &&
        equalsNullable(this.attachments, testResultResponse.attachments) &&
        equalsNullable(this.autoTestId, testResultResponse.autoTestId) &&
        equalsNullable(this.durationInMs, testResultResponse.durationInMs) &&
        equalsNullable(this.traces, testResultResponse.traces) &&
        equalsNullable(this.failureType, testResultResponse.failureType) &&
        equalsNullable(this.message, testResultResponse.message) &&
        equalsNullable(this.autoTest, testResultResponse.autoTest) &&
        equalsNullable(this.autoTestStepResults, testResultResponse.autoTestStepResults) &&
        equalsNullable(this.setupResults, testResultResponse.setupResults) &&
        equalsNullable(this.teardownResults, testResultResponse.teardownResults) &&
        equalsNullable(this.parameters, testResultResponse.parameters) &&
        equalsNullable(this.properties, testResultResponse.properties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, failureClassIds, configurationId, testPointId, testRunId, hashCodeNullable(stepComments), hashCodeNullable(outcome), hashCodeNullable(status), hashCodeNullable(comment), hashCodeNullable(links), hashCodeNullable(stepResults), hashCodeNullable(attachments), hashCodeNullable(autoTestId), hashCodeNullable(durationInMs), hashCodeNullable(traces), hashCodeNullable(failureType), hashCodeNullable(message), hashCodeNullable(autoTest), hashCodeNullable(autoTestStepResults), hashCodeNullable(setupResults), hashCodeNullable(teardownResults), hashCodeNullable(parameters), hashCodeNullable(properties));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestResultResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    failureClassIds: ").append(toIndentedString(failureClassIds)).append("\n");
    sb.append("    configurationId: ").append(toIndentedString(configurationId)).append("\n");
    sb.append("    testPointId: ").append(toIndentedString(testPointId)).append("\n");
    sb.append("    testRunId: ").append(toIndentedString(testRunId)).append("\n");
    sb.append("    stepComments: ").append(toIndentedString(stepComments)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    stepResults: ").append(toIndentedString(stepResults)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    autoTestId: ").append(toIndentedString(autoTestId)).append("\n");
    sb.append("    durationInMs: ").append(toIndentedString(durationInMs)).append("\n");
    sb.append("    traces: ").append(toIndentedString(traces)).append("\n");
    sb.append("    failureType: ").append(toIndentedString(failureType)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    autoTest: ").append(toIndentedString(autoTest)).append("\n");
    sb.append("    autoTestStepResults: ").append(toIndentedString(autoTestStepResults)).append("\n");
    sb.append("    setupResults: ").append(toIndentedString(setupResults)).append("\n");
    sb.append("    teardownResults: ").append(toIndentedString(teardownResults)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

