/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.Int32RangeSelectorModel;
import ru.testit.adaptersapi.model.WorkItemPriorityModel;
import ru.testit.adaptersapi.model.WorkItemSourceTypeModel;
import ru.testit.adaptersapi.model.WorkItemStates;
import ru.testit.adaptersapi.model.WorkItemTypeModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * WorkItemFilterApiModel
 */
@JsonPropertyOrder({
  WorkItemFilterApiModel.JSON_PROPERTY_NAME_OR_ID,
  WorkItemFilterApiModel.JSON_PROPERTY_INCLUDE_IDS,
  WorkItemFilterApiModel.JSON_PROPERTY_EXCLUDE_IDS,
  WorkItemFilterApiModel.JSON_PROPERTY_PROJECT_IDS,
  WorkItemFilterApiModel.JSON_PROPERTY_NAME,
  WorkItemFilterApiModel.JSON_PROPERTY_IDS,
  WorkItemFilterApiModel.JSON_PROPERTY_GLOBAL_IDS,
  WorkItemFilterApiModel.JSON_PROPERTY_ATTRIBUTES,
  WorkItemFilterApiModel.JSON_PROPERTY_IS_DELETED,
  WorkItemFilterApiModel.JSON_PROPERTY_SECTION_IDS,
  WorkItemFilterApiModel.JSON_PROPERTY_STATES,
  WorkItemFilterApiModel.JSON_PROPERTY_PRIORITIES,
  WorkItemFilterApiModel.JSON_PROPERTY_SOURCE_TYPES,
  WorkItemFilterApiModel.JSON_PROPERTY_TYPES,
  WorkItemFilterApiModel.JSON_PROPERTY_DURATION,
  WorkItemFilterApiModel.JSON_PROPERTY_IS_AUTOMATED,
  WorkItemFilterApiModel.JSON_PROPERTY_TAGS,
  WorkItemFilterApiModel.JSON_PROPERTY_EXCLUDE_TAGS,
  WorkItemFilterApiModel.JSON_PROPERTY_AUTO_TEST_IDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class WorkItemFilterApiModel {
  public static final String JSON_PROPERTY_NAME_OR_ID = "nameOrId";
  private JsonNullable<String> nameOrId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INCLUDE_IDS = "includeIds";
  private JsonNullable<Set<UUID>> includeIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_EXCLUDE_IDS = "excludeIds";
  private JsonNullable<Set<UUID>> excludeIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_PROJECT_IDS = "projectIds";
  private JsonNullable<Set<UUID>> projectIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IDS = "ids";
  private JsonNullable<Set<UUID>> ids = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_GLOBAL_IDS = "globalIds";
  private JsonNullable<Set<Long>> globalIds = JsonNullable.<Set<Long>>undefined();

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private JsonNullable<Map<String, Set<String>>> attributes = JsonNullable.<Map<String, Set<String>>>undefined();

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  private JsonNullable<Boolean> isDeleted = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_SECTION_IDS = "sectionIds";
  private JsonNullable<Set<UUID>> sectionIds = JsonNullable.<Set<UUID>>undefined();

  public static final String JSON_PROPERTY_STATES = "states";
  private JsonNullable<Set<WorkItemStates>> states = JsonNullable.<Set<WorkItemStates>>undefined();

  public static final String JSON_PROPERTY_PRIORITIES = "priorities";
  private JsonNullable<Set<WorkItemPriorityModel>> priorities = JsonNullable.<Set<WorkItemPriorityModel>>undefined();

  public static final String JSON_PROPERTY_SOURCE_TYPES = "sourceTypes";
  private JsonNullable<Set<WorkItemSourceTypeModel>> sourceTypes = JsonNullable.<Set<WorkItemSourceTypeModel>>undefined();

  public static final String JSON_PROPERTY_TYPES = "types";
  private JsonNullable<Set<WorkItemTypeModel>> types = JsonNullable.<Set<WorkItemTypeModel>>undefined();

  public static final String JSON_PROPERTY_DURATION = "duration";
  private JsonNullable<Int32RangeSelectorModel> duration = JsonNullable.<Int32RangeSelectorModel>undefined();

  public static final String JSON_PROPERTY_IS_AUTOMATED = "isAutomated";
  private JsonNullable<Boolean> isAutomated = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<Set<String>> tags = JsonNullable.<Set<String>>undefined();

  public static final String JSON_PROPERTY_EXCLUDE_TAGS = "excludeTags";
  private JsonNullable<Set<String>> excludeTags = JsonNullable.<Set<String>>undefined();

  public static final String JSON_PROPERTY_AUTO_TEST_IDS = "autoTestIds";
  private JsonNullable<Set<UUID>> autoTestIds = JsonNullable.<Set<UUID>>undefined();

  public WorkItemFilterApiModel() { 
  }

  public WorkItemFilterApiModel nameOrId(@jakarta.annotation.Nullable String nameOrId) {
    this.nameOrId = JsonNullable.<String>of(nameOrId);
    return this;
  }

  /**
   * Name or identifier (UUID) of work item
   * @return nameOrId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getNameOrId() {
        return nameOrId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME_OR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNameOrId_JsonNullable() {
    return nameOrId;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME_OR_ID)
  public void setNameOrId_JsonNullable(JsonNullable<String> nameOrId) {
    this.nameOrId = nameOrId;
  }

  public void setNameOrId(@jakarta.annotation.Nullable String nameOrId) {
    this.nameOrId = JsonNullable.<String>of(nameOrId);
  }


  public WorkItemFilterApiModel includeIds(@jakarta.annotation.Nullable Set<UUID> includeIds) {
    this.includeIds = JsonNullable.<Set<UUID>>of(includeIds);
    return this;
  }

  public WorkItemFilterApiModel addIncludeIdsItem(UUID includeIdsItem) {
    if (this.includeIds == null || !this.includeIds.isPresent()) {
      this.includeIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.includeIds.get().add(includeIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of identifiers of work items which need to be included in result regardless of filtering
   * @return includeIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getIncludeIds() {
        return includeIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INCLUDE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getIncludeIds_JsonNullable() {
    return includeIds;
  }
  
  @JsonProperty(JSON_PROPERTY_INCLUDE_IDS)
  public void setIncludeIds_JsonNullable(JsonNullable<Set<UUID>> includeIds) {
    this.includeIds = includeIds;
  }

  public void setIncludeIds(@jakarta.annotation.Nullable Set<UUID> includeIds) {
    this.includeIds = JsonNullable.<Set<UUID>>of(includeIds);
  }


  public WorkItemFilterApiModel excludeIds(@jakarta.annotation.Nullable Set<UUID> excludeIds) {
    this.excludeIds = JsonNullable.<Set<UUID>>of(excludeIds);
    return this;
  }

  public WorkItemFilterApiModel addExcludeIdsItem(UUID excludeIdsItem) {
    if (this.excludeIds == null || !this.excludeIds.isPresent()) {
      this.excludeIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.excludeIds.get().add(excludeIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of identifiers of work items which need to be excluded from result regardless of filtering
   * @return excludeIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getExcludeIds() {
        return excludeIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXCLUDE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getExcludeIds_JsonNullable() {
    return excludeIds;
  }
  
  @JsonProperty(JSON_PROPERTY_EXCLUDE_IDS)
  public void setExcludeIds_JsonNullable(JsonNullable<Set<UUID>> excludeIds) {
    this.excludeIds = excludeIds;
  }

  public void setExcludeIds(@jakarta.annotation.Nullable Set<UUID> excludeIds) {
    this.excludeIds = JsonNullable.<Set<UUID>>of(excludeIds);
  }


  public WorkItemFilterApiModel projectIds(@jakarta.annotation.Nullable Set<UUID> projectIds) {
    this.projectIds = JsonNullable.<Set<UUID>>of(projectIds);
    return this;
  }

  public WorkItemFilterApiModel addProjectIdsItem(UUID projectIdsItem) {
    if (this.projectIds == null || !this.projectIds.isPresent()) {
      this.projectIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.projectIds.get().add(projectIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of project identifiers
   * @return projectIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getProjectIds() {
        return projectIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROJECT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getProjectIds_JsonNullable() {
    return projectIds;
  }
  
  @JsonProperty(JSON_PROPERTY_PROJECT_IDS)
  public void setProjectIds_JsonNullable(JsonNullable<Set<UUID>> projectIds) {
    this.projectIds = projectIds;
  }

  public void setProjectIds(@jakarta.annotation.Nullable Set<UUID> projectIds) {
    this.projectIds = JsonNullable.<Set<UUID>>of(projectIds);
  }


  public WorkItemFilterApiModel name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Name of work item
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public WorkItemFilterApiModel ids(@jakarta.annotation.Nullable Set<UUID> ids) {
    this.ids = JsonNullable.<Set<UUID>>of(ids);
    return this;
  }

  public WorkItemFilterApiModel addIdsItem(UUID idsItem) {
    if (this.ids == null || !this.ids.isPresent()) {
      this.ids = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.ids.get().add(idsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies a work item unique IDs to search for
   * @return ids
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getIds() {
        return ids.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getIds_JsonNullable() {
    return ids;
  }
  
  @JsonProperty(JSON_PROPERTY_IDS)
  public void setIds_JsonNullable(JsonNullable<Set<UUID>> ids) {
    this.ids = ids;
  }

  public void setIds(@jakarta.annotation.Nullable Set<UUID> ids) {
    this.ids = JsonNullable.<Set<UUID>>of(ids);
  }


  public WorkItemFilterApiModel globalIds(@jakarta.annotation.Nullable Set<Long> globalIds) {
    this.globalIds = JsonNullable.<Set<Long>>of(globalIds);
    return this;
  }

  public WorkItemFilterApiModel addGlobalIdsItem(Long globalIdsItem) {
    if (this.globalIds == null || !this.globalIds.isPresent()) {
      this.globalIds = JsonNullable.<Set<Long>>of(new LinkedHashSet<>());
    }
    try {
      this.globalIds.get().add(globalIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of global (integer) identifiers
   * @return globalIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<Long> getGlobalIds() {
        return globalIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GLOBAL_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<Long>> getGlobalIds_JsonNullable() {
    return globalIds;
  }
  
  @JsonProperty(JSON_PROPERTY_GLOBAL_IDS)
  public void setGlobalIds_JsonNullable(JsonNullable<Set<Long>> globalIds) {
    this.globalIds = globalIds;
  }

  public void setGlobalIds(@jakarta.annotation.Nullable Set<Long> globalIds) {
    this.globalIds = JsonNullable.<Set<Long>>of(globalIds);
  }


  public WorkItemFilterApiModel attributes(@jakarta.annotation.Nullable Map<String, Set<String>> attributes) {
    this.attributes = JsonNullable.<Map<String, Set<String>>>of(attributes);
    return this;
  }

  public WorkItemFilterApiModel putAttributesItem(String key, Set<String> attributesItem) {
    if (this.attributes == null || !this.attributes.isPresent()) {
      this.attributes = JsonNullable.<Map<String, Set<String>>>of(new HashMap<>());
    }
    try {
      this.attributes.get().put(key, attributesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Custom attributes of work item
   * @return attributes
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, Set<String>> getAttributes() {
        return attributes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Set<String>>> getAttributes_JsonNullable() {
    return attributes;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  public void setAttributes_JsonNullable(JsonNullable<Map<String, Set<String>>> attributes) {
    this.attributes = attributes;
  }

  public void setAttributes(@jakarta.annotation.Nullable Map<String, Set<String>> attributes) {
    this.attributes = JsonNullable.<Map<String, Set<String>>>of(attributes);
  }


  public WorkItemFilterApiModel isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
    return this;
  }

  /**
   * Is result must consist of only actual/deleted work items
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsDeleted() {
        return isDeleted.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsDeleted_JsonNullable() {
    return isDeleted;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  public void setIsDeleted_JsonNullable(JsonNullable<Boolean> isDeleted) {
    this.isDeleted = isDeleted;
  }

  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = JsonNullable.<Boolean>of(isDeleted);
  }


  public WorkItemFilterApiModel sectionIds(@jakarta.annotation.Nullable Set<UUID> sectionIds) {
    this.sectionIds = JsonNullable.<Set<UUID>>of(sectionIds);
    return this;
  }

  public WorkItemFilterApiModel addSectionIdsItem(UUID sectionIdsItem) {
    if (this.sectionIds == null || !this.sectionIds.isPresent()) {
      this.sectionIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.sectionIds.get().add(sectionIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of section identifiers
   * @return sectionIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getSectionIds() {
        return sectionIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SECTION_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getSectionIds_JsonNullable() {
    return sectionIds;
  }
  
  @JsonProperty(JSON_PROPERTY_SECTION_IDS)
  public void setSectionIds_JsonNullable(JsonNullable<Set<UUID>> sectionIds) {
    this.sectionIds = sectionIds;
  }

  public void setSectionIds(@jakarta.annotation.Nullable Set<UUID> sectionIds) {
    this.sectionIds = JsonNullable.<Set<UUID>>of(sectionIds);
  }


  public WorkItemFilterApiModel states(@jakarta.annotation.Nullable Set<WorkItemStates> states) {
    this.states = JsonNullable.<Set<WorkItemStates>>of(states);
    return this;
  }

  public WorkItemFilterApiModel addStatesItem(WorkItemStates statesItem) {
    if (this.states == null || !this.states.isPresent()) {
      this.states = JsonNullable.<Set<WorkItemStates>>of(new LinkedHashSet<>());
    }
    try {
      this.states.get().add(statesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of states of work item
   * @return states
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<WorkItemStates> getStates() {
        return states.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<WorkItemStates>> getStates_JsonNullable() {
    return states;
  }
  
  @JsonProperty(JSON_PROPERTY_STATES)
  public void setStates_JsonNullable(JsonNullable<Set<WorkItemStates>> states) {
    this.states = states;
  }

  public void setStates(@jakarta.annotation.Nullable Set<WorkItemStates> states) {
    this.states = JsonNullable.<Set<WorkItemStates>>of(states);
  }


  public WorkItemFilterApiModel priorities(@jakarta.annotation.Nullable Set<WorkItemPriorityModel> priorities) {
    this.priorities = JsonNullable.<Set<WorkItemPriorityModel>>of(priorities);
    return this;
  }

  public WorkItemFilterApiModel addPrioritiesItem(WorkItemPriorityModel prioritiesItem) {
    if (this.priorities == null || !this.priorities.isPresent()) {
      this.priorities = JsonNullable.<Set<WorkItemPriorityModel>>of(new LinkedHashSet<>());
    }
    try {
      this.priorities.get().add(prioritiesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of priorities of work item
   * @return priorities
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<WorkItemPriorityModel> getPriorities() {
        return priorities.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PRIORITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<WorkItemPriorityModel>> getPriorities_JsonNullable() {
    return priorities;
  }
  
  @JsonProperty(JSON_PROPERTY_PRIORITIES)
  public void setPriorities_JsonNullable(JsonNullable<Set<WorkItemPriorityModel>> priorities) {
    this.priorities = priorities;
  }

  public void setPriorities(@jakarta.annotation.Nullable Set<WorkItemPriorityModel> priorities) {
    this.priorities = JsonNullable.<Set<WorkItemPriorityModel>>of(priorities);
  }


  public WorkItemFilterApiModel sourceTypes(@jakarta.annotation.Nullable Set<WorkItemSourceTypeModel> sourceTypes) {
    this.sourceTypes = JsonNullable.<Set<WorkItemSourceTypeModel>>of(sourceTypes);
    return this;
  }

  public WorkItemFilterApiModel addSourceTypesItem(WorkItemSourceTypeModel sourceTypesItem) {
    if (this.sourceTypes == null || !this.sourceTypes.isPresent()) {
      this.sourceTypes = JsonNullable.<Set<WorkItemSourceTypeModel>>of(new LinkedHashSet<>());
    }
    try {
      this.sourceTypes.get().add(sourceTypesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Source type of work item (manual creation or AI generated)
   * @return sourceTypes
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<WorkItemSourceTypeModel> getSourceTypes() {
        return sourceTypes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SOURCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<WorkItemSourceTypeModel>> getSourceTypes_JsonNullable() {
    return sourceTypes;
  }
  
  @JsonProperty(JSON_PROPERTY_SOURCE_TYPES)
  public void setSourceTypes_JsonNullable(JsonNullable<Set<WorkItemSourceTypeModel>> sourceTypes) {
    this.sourceTypes = sourceTypes;
  }

  public void setSourceTypes(@jakarta.annotation.Nullable Set<WorkItemSourceTypeModel> sourceTypes) {
    this.sourceTypes = JsonNullable.<Set<WorkItemSourceTypeModel>>of(sourceTypes);
  }


  public WorkItemFilterApiModel types(@jakarta.annotation.Nullable Set<WorkItemTypeModel> types) {
    this.types = JsonNullable.<Set<WorkItemTypeModel>>of(types);
    return this;
  }

  public WorkItemFilterApiModel addTypesItem(WorkItemTypeModel typesItem) {
    if (this.types == null || !this.types.isPresent()) {
      this.types = JsonNullable.<Set<WorkItemTypeModel>>of(new LinkedHashSet<>());
    }
    try {
      this.types.get().add(typesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of types of work item
   * @return types
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<WorkItemTypeModel> getTypes() {
        return types.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<WorkItemTypeModel>> getTypes_JsonNullable() {
    return types;
  }
  
  @JsonProperty(JSON_PROPERTY_TYPES)
  public void setTypes_JsonNullable(JsonNullable<Set<WorkItemTypeModel>> types) {
    this.types = types;
  }

  public void setTypes(@jakarta.annotation.Nullable Set<WorkItemTypeModel> types) {
    this.types = JsonNullable.<Set<WorkItemTypeModel>>of(types);
  }


  public WorkItemFilterApiModel duration(@jakarta.annotation.Nullable Int32RangeSelectorModel duration) {
    this.duration = JsonNullable.<Int32RangeSelectorModel>of(duration);
    return this;
  }

  /**
   * Specifies a work item duration range to search for
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Int32RangeSelectorModel getDuration() {
        return duration.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Int32RangeSelectorModel> getDuration_JsonNullable() {
    return duration;
  }
  
  @JsonProperty(JSON_PROPERTY_DURATION)
  public void setDuration_JsonNullable(JsonNullable<Int32RangeSelectorModel> duration) {
    this.duration = duration;
  }

  public void setDuration(@jakarta.annotation.Nullable Int32RangeSelectorModel duration) {
    this.duration = JsonNullable.<Int32RangeSelectorModel>of(duration);
  }


  public WorkItemFilterApiModel isAutomated(@jakarta.annotation.Nullable Boolean isAutomated) {
    this.isAutomated = JsonNullable.<Boolean>of(isAutomated);
    return this;
  }

  /**
   * Is result must consist of only manual/automated work items
   * @return isAutomated
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsAutomated() {
        return isAutomated.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_AUTOMATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsAutomated_JsonNullable() {
    return isAutomated;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_AUTOMATED)
  public void setIsAutomated_JsonNullable(JsonNullable<Boolean> isAutomated) {
    this.isAutomated = isAutomated;
  }

  public void setIsAutomated(@jakarta.annotation.Nullable Boolean isAutomated) {
    this.isAutomated = JsonNullable.<Boolean>of(isAutomated);
  }


  public WorkItemFilterApiModel tags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = JsonNullable.<Set<String>>of(tags);
    return this;
  }

  public WorkItemFilterApiModel addTagsItem(String tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<Set<String>>of(new LinkedHashSet<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<String> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<String>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<Set<String>> tags) {
    this.tags = tags;
  }

  public void setTags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = JsonNullable.<Set<String>>of(tags);
  }


  public WorkItemFilterApiModel excludeTags(@jakarta.annotation.Nullable Set<String> excludeTags) {
    this.excludeTags = JsonNullable.<Set<String>>of(excludeTags);
    return this;
  }

  public WorkItemFilterApiModel addExcludeTagsItem(String excludeTagsItem) {
    if (this.excludeTags == null || !this.excludeTags.isPresent()) {
      this.excludeTags = JsonNullable.<Set<String>>of(new LinkedHashSet<>());
    }
    try {
      this.excludeTags.get().add(excludeTagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of tags to exclude
   * @return excludeTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<String> getExcludeTags() {
        return excludeTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXCLUDE_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<String>> getExcludeTags_JsonNullable() {
    return excludeTags;
  }
  
  @JsonProperty(JSON_PROPERTY_EXCLUDE_TAGS)
  public void setExcludeTags_JsonNullable(JsonNullable<Set<String>> excludeTags) {
    this.excludeTags = excludeTags;
  }

  public void setExcludeTags(@jakarta.annotation.Nullable Set<String> excludeTags) {
    this.excludeTags = JsonNullable.<Set<String>>of(excludeTags);
  }


  public WorkItemFilterApiModel autoTestIds(@jakarta.annotation.Nullable Set<UUID> autoTestIds) {
    this.autoTestIds = JsonNullable.<Set<UUID>>of(autoTestIds);
    return this;
  }

  public WorkItemFilterApiModel addAutoTestIdsItem(UUID autoTestIdsItem) {
    if (this.autoTestIds == null || !this.autoTestIds.isPresent()) {
      this.autoTestIds = JsonNullable.<Set<UUID>>of(new LinkedHashSet<>());
    }
    try {
      this.autoTestIds.get().add(autoTestIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Collection of identifiers of linked autotests
   * @return autoTestIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<UUID> getAutoTestIds() {
        return autoTestIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AUTO_TEST_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<UUID>> getAutoTestIds_JsonNullable() {
    return autoTestIds;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTO_TEST_IDS)
  public void setAutoTestIds_JsonNullable(JsonNullable<Set<UUID>> autoTestIds) {
    this.autoTestIds = autoTestIds;
  }

  public void setAutoTestIds(@jakarta.annotation.Nullable Set<UUID> autoTestIds) {
    this.autoTestIds = JsonNullable.<Set<UUID>>of(autoTestIds);
  }


  /**
   * Return true if this WorkItemFilterApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemFilterApiModel workItemFilterApiModel = (WorkItemFilterApiModel) o;
    return equalsNullable(this.nameOrId, workItemFilterApiModel.nameOrId) &&
        equalsNullable(this.includeIds, workItemFilterApiModel.includeIds) &&
        equalsNullable(this.excludeIds, workItemFilterApiModel.excludeIds) &&
        equalsNullable(this.projectIds, workItemFilterApiModel.projectIds) &&
        equalsNullable(this.name, workItemFilterApiModel.name) &&
        equalsNullable(this.ids, workItemFilterApiModel.ids) &&
        equalsNullable(this.globalIds, workItemFilterApiModel.globalIds) &&
        equalsNullable(this.attributes, workItemFilterApiModel.attributes) &&
        equalsNullable(this.isDeleted, workItemFilterApiModel.isDeleted) &&
        equalsNullable(this.sectionIds, workItemFilterApiModel.sectionIds) &&
        equalsNullable(this.states, workItemFilterApiModel.states) &&
        equalsNullable(this.priorities, workItemFilterApiModel.priorities) &&
        equalsNullable(this.sourceTypes, workItemFilterApiModel.sourceTypes) &&
        equalsNullable(this.types, workItemFilterApiModel.types) &&
        equalsNullable(this.duration, workItemFilterApiModel.duration) &&
        equalsNullable(this.isAutomated, workItemFilterApiModel.isAutomated) &&
        equalsNullable(this.tags, workItemFilterApiModel.tags) &&
        equalsNullable(this.excludeTags, workItemFilterApiModel.excludeTags) &&
        equalsNullable(this.autoTestIds, workItemFilterApiModel.autoTestIds);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(nameOrId), hashCodeNullable(includeIds), hashCodeNullable(excludeIds), hashCodeNullable(projectIds), hashCodeNullable(name), hashCodeNullable(ids), hashCodeNullable(globalIds), hashCodeNullable(attributes), hashCodeNullable(isDeleted), hashCodeNullable(sectionIds), hashCodeNullable(states), hashCodeNullable(priorities), hashCodeNullable(sourceTypes), hashCodeNullable(types), hashCodeNullable(duration), hashCodeNullable(isAutomated), hashCodeNullable(tags), hashCodeNullable(excludeTags), hashCodeNullable(autoTestIds));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemFilterApiModel {\n");
    sb.append("    nameOrId: ").append(toIndentedString(nameOrId)).append("\n");
    sb.append("    includeIds: ").append(toIndentedString(includeIds)).append("\n");
    sb.append("    excludeIds: ").append(toIndentedString(excludeIds)).append("\n");
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    globalIds: ").append(toIndentedString(globalIds)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    sectionIds: ").append(toIndentedString(sectionIds)).append("\n");
    sb.append("    states: ").append(toIndentedString(states)).append("\n");
    sb.append("    priorities: ").append(toIndentedString(priorities)).append("\n");
    sb.append("    sourceTypes: ").append(toIndentedString(sourceTypes)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    isAutomated: ").append(toIndentedString(isAutomated)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    excludeTags: ").append(toIndentedString(excludeTags)).append("\n");
    sb.append("    autoTestIds: ").append(toIndentedString(autoTestIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

