/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.adaptersapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.adaptersapi.model.IterationApiResult;
import ru.testit.adaptersapi.model.LinkShortApiResult;
import ru.testit.adaptersapi.model.WorkItemPriorityModel;
import ru.testit.adaptersapi.model.WorkItemSourceTypeModel;
import ru.testit.adaptersapi.model.WorkItemStates;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.adaptersapi.invoker.JSON;


/**
 * WorkItemShortApiResult
 */
@JsonPropertyOrder({
  WorkItemShortApiResult.JSON_PROPERTY_ID,
  WorkItemShortApiResult.JSON_PROPERTY_NAME,
  WorkItemShortApiResult.JSON_PROPERTY_ENTITY_TYPE_NAME,
  WorkItemShortApiResult.JSON_PROPERTY_PROJECT_ID,
  WorkItemShortApiResult.JSON_PROPERTY_SECTION_ID,
  WorkItemShortApiResult.JSON_PROPERTY_SECTION_NAME,
  WorkItemShortApiResult.JSON_PROPERTY_IS_AUTOMATED,
  WorkItemShortApiResult.JSON_PROPERTY_GLOBAL_ID,
  WorkItemShortApiResult.JSON_PROPERTY_DURATION,
  WorkItemShortApiResult.JSON_PROPERTY_STATE,
  WorkItemShortApiResult.JSON_PROPERTY_PRIORITY,
  WorkItemShortApiResult.JSON_PROPERTY_SOURCE_TYPE,
  WorkItemShortApiResult.JSON_PROPERTY_IS_DELETED,
  WorkItemShortApiResult.JSON_PROPERTY_ITERATIONS,
  WorkItemShortApiResult.JSON_PROPERTY_LINKS,
  WorkItemShortApiResult.JSON_PROPERTY_ATTRIBUTES,
  WorkItemShortApiResult.JSON_PROPERTY_TAG_NAMES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class WorkItemShortApiResult {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_ENTITY_TYPE_NAME = "entityTypeName";
  @jakarta.annotation.Nonnull
  private String entityTypeName;

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @jakarta.annotation.Nonnull
  private UUID projectId;

  public static final String JSON_PROPERTY_SECTION_ID = "sectionId";
  @jakarta.annotation.Nonnull
  private UUID sectionId;

  public static final String JSON_PROPERTY_SECTION_NAME = "sectionName";
  @jakarta.annotation.Nonnull
  private String sectionName;

  public static final String JSON_PROPERTY_IS_AUTOMATED = "isAutomated";
  @jakarta.annotation.Nonnull
  private Boolean isAutomated;

  public static final String JSON_PROPERTY_GLOBAL_ID = "globalId";
  @jakarta.annotation.Nonnull
  private Long globalId;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nonnull
  private Long duration;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nonnull
  private WorkItemStates state;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  @jakarta.annotation.Nonnull
  private WorkItemPriorityModel priority;

  public static final String JSON_PROPERTY_SOURCE_TYPE = "sourceType";
  @jakarta.annotation.Nonnull
  private WorkItemSourceTypeModel sourceType;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nonnull
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_ITERATIONS = "iterations";
  @jakarta.annotation.Nonnull
  private List<IterationApiResult> iterations = new ArrayList<>();

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nonnull
  private List<LinkShortApiResult> links = new ArrayList<>();

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private JsonNullable<Map<String, Object>> attributes = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_TAG_NAMES = "tagNames";
  private JsonNullable<List<String>> tagNames = JsonNullable.<List<String>>undefined();

  public WorkItemShortApiResult() { 
  }

  public WorkItemShortApiResult id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Work Item internal unique identifier
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public WorkItemShortApiResult name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Work Item name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public WorkItemShortApiResult entityTypeName(@jakarta.annotation.Nonnull String entityTypeName) {
    this.entityTypeName = entityTypeName;
    return this;
  }

  /**
   * Work Item type. Possible values: CheckLists, SharedSteps, TestCases
   * @return entityTypeName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTITY_TYPE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntityTypeName() {
    return entityTypeName;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_TYPE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntityTypeName(@jakarta.annotation.Nonnull String entityTypeName) {
    this.entityTypeName = entityTypeName;
  }


  public WorkItemShortApiResult projectId(@jakarta.annotation.Nonnull UUID projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Project unique identifier
   * @return projectId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@jakarta.annotation.Nonnull UUID projectId) {
    this.projectId = projectId;
  }


  public WorkItemShortApiResult sectionId(@jakarta.annotation.Nonnull UUID sectionId) {
    this.sectionId = sectionId;
    return this;
  }

  /**
   * Identifier of Section where Work Item is located
   * @return sectionId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getSectionId() {
    return sectionId;
  }


  @JsonProperty(JSON_PROPERTY_SECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSectionId(@jakarta.annotation.Nonnull UUID sectionId) {
    this.sectionId = sectionId;
  }


  public WorkItemShortApiResult sectionName(@jakarta.annotation.Nonnull String sectionName) {
    this.sectionName = sectionName;
    return this;
  }

  /**
   * Section name of Work Item
   * @return sectionName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SECTION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSectionName() {
    return sectionName;
  }


  @JsonProperty(JSON_PROPERTY_SECTION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSectionName(@jakarta.annotation.Nonnull String sectionName) {
    this.sectionName = sectionName;
  }


  public WorkItemShortApiResult isAutomated(@jakarta.annotation.Nonnull Boolean isAutomated) {
    this.isAutomated = isAutomated;
    return this;
  }

  /**
   * Boolean flag determining whether Work Item is automated
   * @return isAutomated
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_AUTOMATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsAutomated() {
    return isAutomated;
  }


  @JsonProperty(JSON_PROPERTY_IS_AUTOMATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsAutomated(@jakarta.annotation.Nonnull Boolean isAutomated) {
    this.isAutomated = isAutomated;
  }


  public WorkItemShortApiResult globalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
    return this;
  }

  /**
   * Work Item global identifier
   * @return globalId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getGlobalId() {
    return globalId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGlobalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
  }


  public WorkItemShortApiResult duration(@jakarta.annotation.Nonnull Long duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Work Item duration
   * @return duration
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDuration(@jakarta.annotation.Nonnull Long duration) {
    this.duration = duration;
  }


  public WorkItemShortApiResult state(@jakarta.annotation.Nonnull WorkItemStates state) {
    this.state = state;
    return this;
  }

  /**
   * The current state of Work Item
   * @return state
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WorkItemStates getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@jakarta.annotation.Nonnull WorkItemStates state) {
    this.state = state;
  }


  public WorkItemShortApiResult priority(@jakarta.annotation.Nonnull WorkItemPriorityModel priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Work Item priority level
   * @return priority
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WorkItemPriorityModel getPriority() {
    return priority;
  }


  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPriority(@jakarta.annotation.Nonnull WorkItemPriorityModel priority) {
    this.priority = priority;
  }


  public WorkItemShortApiResult sourceType(@jakarta.annotation.Nonnull WorkItemSourceTypeModel sourceType) {
    this.sourceType = sourceType;
    return this;
  }

  /**
   * Work Item priority level
   * @return sourceType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WorkItemSourceTypeModel getSourceType() {
    return sourceType;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceType(@jakarta.annotation.Nonnull WorkItemSourceTypeModel sourceType) {
    this.sourceType = sourceType;
  }


  public WorkItemShortApiResult isDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Flag determining whether Work Item is deleted
   * @return isDeleted
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public WorkItemShortApiResult iterations(@jakarta.annotation.Nonnull List<IterationApiResult> iterations) {
    this.iterations = iterations;
    return this;
  }

  public WorkItemShortApiResult addIterationsItem(IterationApiResult iterationsItem) {
    if (this.iterations == null) {
      this.iterations = new ArrayList<>();
    }
    this.iterations.add(iterationsItem);
    return this;
  }

  /**
   * Set of iterations related to Work Item
   * @return iterations
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ITERATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<IterationApiResult> getIterations() {
    return iterations;
  }


  @JsonProperty(JSON_PROPERTY_ITERATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIterations(@jakarta.annotation.Nonnull List<IterationApiResult> iterations) {
    this.iterations = iterations;
  }


  public WorkItemShortApiResult links(@jakarta.annotation.Nonnull List<LinkShortApiResult> links) {
    this.links = links;
    return this;
  }

  public WorkItemShortApiResult addLinksItem(LinkShortApiResult linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Set of links related to Work Item
   * @return links
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<LinkShortApiResult> getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLinks(@jakarta.annotation.Nonnull List<LinkShortApiResult> links) {
    this.links = links;
  }


  public WorkItemShortApiResult attributes(@jakarta.annotation.Nullable Map<String, Object> attributes) {
    this.attributes = JsonNullable.<Map<String, Object>>of(attributes);
    return this;
  }

  public WorkItemShortApiResult putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null || !this.attributes.isPresent()) {
      this.attributes = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.attributes.get().put(key, attributesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Work Item attributes
   * @return attributes
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, Object> getAttributes() {
        return attributes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getAttributes_JsonNullable() {
    return attributes;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  public void setAttributes_JsonNullable(JsonNullable<Map<String, Object>> attributes) {
    this.attributes = attributes;
  }

  public void setAttributes(@jakarta.annotation.Nullable Map<String, Object> attributes) {
    this.attributes = JsonNullable.<Map<String, Object>>of(attributes);
  }


  public WorkItemShortApiResult tagNames(@jakarta.annotation.Nullable List<String> tagNames) {
    this.tagNames = JsonNullable.<List<String>>of(tagNames);
    return this;
  }

  public WorkItemShortApiResult addTagNamesItem(String tagNamesItem) {
    if (this.tagNames == null || !this.tagNames.isPresent()) {
      this.tagNames = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.tagNames.get().add(tagNamesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Array of tag names of Work Item
   * @return tagNames
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<String> getTagNames() {
        return tagNames.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAG_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getTagNames_JsonNullable() {
    return tagNames;
  }
  
  @JsonProperty(JSON_PROPERTY_TAG_NAMES)
  public void setTagNames_JsonNullable(JsonNullable<List<String>> tagNames) {
    this.tagNames = tagNames;
  }

  public void setTagNames(@jakarta.annotation.Nullable List<String> tagNames) {
    this.tagNames = JsonNullable.<List<String>>of(tagNames);
  }


  /**
   * Return true if this WorkItemShortApiResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemShortApiResult workItemShortApiResult = (WorkItemShortApiResult) o;
    return Objects.equals(this.id, workItemShortApiResult.id) &&
        Objects.equals(this.name, workItemShortApiResult.name) &&
        Objects.equals(this.entityTypeName, workItemShortApiResult.entityTypeName) &&
        Objects.equals(this.projectId, workItemShortApiResult.projectId) &&
        Objects.equals(this.sectionId, workItemShortApiResult.sectionId) &&
        Objects.equals(this.sectionName, workItemShortApiResult.sectionName) &&
        Objects.equals(this.isAutomated, workItemShortApiResult.isAutomated) &&
        Objects.equals(this.globalId, workItemShortApiResult.globalId) &&
        Objects.equals(this.duration, workItemShortApiResult.duration) &&
        Objects.equals(this.state, workItemShortApiResult.state) &&
        Objects.equals(this.priority, workItemShortApiResult.priority) &&
        Objects.equals(this.sourceType, workItemShortApiResult.sourceType) &&
        Objects.equals(this.isDeleted, workItemShortApiResult.isDeleted) &&
        Objects.equals(this.iterations, workItemShortApiResult.iterations) &&
        Objects.equals(this.links, workItemShortApiResult.links) &&
        equalsNullable(this.attributes, workItemShortApiResult.attributes) &&
        equalsNullable(this.tagNames, workItemShortApiResult.tagNames);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, entityTypeName, projectId, sectionId, sectionName, isAutomated, globalId, duration, state, priority, sourceType, isDeleted, iterations, links, hashCodeNullable(attributes), hashCodeNullable(tagNames));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemShortApiResult {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    entityTypeName: ").append(toIndentedString(entityTypeName)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    sectionId: ").append(toIndentedString(sectionId)).append("\n");
    sb.append("    sectionName: ").append(toIndentedString(sectionName)).append("\n");
    sb.append("    isAutomated: ").append(toIndentedString(isAutomated)).append("\n");
    sb.append("    globalId: ").append(toIndentedString(globalId)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    iterations: ").append(toIndentedString(iterations)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    tagNames: ").append(toIndentedString(tagNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

