/*
 * Sync Storage Service API
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.syncstorage.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.syncstorage.invoker.JSON;


/**
 * RegisterRequest
 */
@JsonPropertyOrder({
  RegisterRequest.JSON_PROPERTY_PID,
  RegisterRequest.JSON_PROPERTY_TEST_RUN_ID,
  RegisterRequest.JSON_PROPERTY_BASE_URL,
  RegisterRequest.JSON_PROPERTY_PRIVATE_TOKEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class RegisterRequest {
  public static final String JSON_PROPERTY_PID = "pid";
  @jakarta.annotation.Nullable
  private String pid;

  public static final String JSON_PROPERTY_TEST_RUN_ID = "testRunId";
  @jakarta.annotation.Nullable
  private String testRunId;

  public static final String JSON_PROPERTY_BASE_URL = "baseUrl";
  @jakarta.annotation.Nullable
  private String baseUrl;

  public static final String JSON_PROPERTY_PRIVATE_TOKEN = "privateToken";
  @jakarta.annotation.Nullable
  private String privateToken;

  public RegisterRequest() { 
  }

  public RegisterRequest pid(@jakarta.annotation.Nullable String pid) {
    this.pid = pid;
    return this;
  }

  /**
   * Get pid
   * @return pid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPid() {
    return pid;
  }


  @JsonProperty(JSON_PROPERTY_PID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPid(@jakarta.annotation.Nullable String pid) {
    this.pid = pid;
  }


  public RegisterRequest testRunId(@jakarta.annotation.Nullable String testRunId) {
    this.testRunId = testRunId;
    return this;
  }

  /**
   * Get testRunId
   * @return testRunId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEST_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTestRunId() {
    return testRunId;
  }


  @JsonProperty(JSON_PROPERTY_TEST_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTestRunId(@jakarta.annotation.Nullable String testRunId) {
    this.testRunId = testRunId;
  }


  public RegisterRequest baseUrl(@jakarta.annotation.Nullable String baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

  /**
   * Get baseUrl
   * @return baseUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BASE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBaseUrl() {
    return baseUrl;
  }


  @JsonProperty(JSON_PROPERTY_BASE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseUrl(@jakarta.annotation.Nullable String baseUrl) {
    this.baseUrl = baseUrl;
  }


  public RegisterRequest privateToken(@jakarta.annotation.Nullable String privateToken) {
    this.privateToken = privateToken;
    return this;
  }

  /**
   * Get privateToken
   * @return privateToken
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRIVATE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrivateToken() {
    return privateToken;
  }


  @JsonProperty(JSON_PROPERTY_PRIVATE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrivateToken(@jakarta.annotation.Nullable String privateToken) {
    this.privateToken = privateToken;
  }


  /**
   * Return true if this RegisterRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisterRequest registerRequest = (RegisterRequest) o;
    return Objects.equals(this.pid, registerRequest.pid) &&
        Objects.equals(this.testRunId, registerRequest.testRunId) &&
        Objects.equals(this.baseUrl, registerRequest.baseUrl) &&
        Objects.equals(this.privateToken, registerRequest.privateToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pid, testRunId, baseUrl, privateToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisterRequest {\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    testRunId: ").append(toIndentedString(testRunId)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    privateToken: ").append(toIndentedString(privateToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

