/*
 * Sync Storage Service API
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.syncstorage.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.syncstorage.invoker.JSON;


/**
 * SetWorkerStatusRequest
 */
@JsonPropertyOrder({
  SetWorkerStatusRequest.JSON_PROPERTY_PID,
  SetWorkerStatusRequest.JSON_PROPERTY_STATUS,
  SetWorkerStatusRequest.JSON_PROPERTY_TEST_RUN_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class SetWorkerStatusRequest {
  public static final String JSON_PROPERTY_PID = "pid";
  @jakarta.annotation.Nullable
  private String pid;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_TEST_RUN_ID = "testRunId";
  @jakarta.annotation.Nullable
  private String testRunId;

  public SetWorkerStatusRequest() { 
  }

  public SetWorkerStatusRequest pid(@jakarta.annotation.Nullable String pid) {
    this.pid = pid;
    return this;
  }

  /**
   * Get pid
   * @return pid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPid() {
    return pid;
  }


  @JsonProperty(value = JSON_PROPERTY_PID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPid(@jakarta.annotation.Nullable String pid) {
    this.pid = pid;
  }


  public SetWorkerStatusRequest status(@jakarta.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public SetWorkerStatusRequest testRunId(@jakarta.annotation.Nullable String testRunId) {
    this.testRunId = testRunId;
    return this;
  }

  /**
   * Get testRunId
   * @return testRunId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEST_RUN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTestRunId() {
    return testRunId;
  }


  @JsonProperty(value = JSON_PROPERTY_TEST_RUN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTestRunId(@jakarta.annotation.Nullable String testRunId) {
    this.testRunId = testRunId;
  }


  /**
   * Return true if this SetWorkerStatusRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetWorkerStatusRequest setWorkerStatusRequest = (SetWorkerStatusRequest) o;
    return Objects.equals(this.pid, setWorkerStatusRequest.pid) &&
        Objects.equals(this.status, setWorkerStatusRequest.status) &&
        Objects.equals(this.testRunId, setWorkerStatusRequest.testRunId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pid, status, testRunId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetWorkerStatusRequest {\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    testRunId: ").append(toIndentedString(testRunId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

