/*
 * Sync Storage Service API
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.syncstorage.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.syncstorage.invoker.JSON;


/**
 * TestResultCutApiModel
 */
@JsonPropertyOrder({
  TestResultCutApiModel.JSON_PROPERTY_PROJECT_ID,
  TestResultCutApiModel.JSON_PROPERTY_AUTO_TEST_EXTERNAL_ID,
  TestResultCutApiModel.JSON_PROPERTY_STATUS_CODE,
  TestResultCutApiModel.JSON_PROPERTY_STATUS_TYPE,
  TestResultCutApiModel.JSON_PROPERTY_STARTED_ON
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class TestResultCutApiModel {
  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @jakarta.annotation.Nullable
  private String projectId;

  public static final String JSON_PROPERTY_AUTO_TEST_EXTERNAL_ID = "autoTestExternalId";
  @jakarta.annotation.Nullable
  private String autoTestExternalId;

  public static final String JSON_PROPERTY_STATUS_CODE = "statusCode";
  @jakarta.annotation.Nullable
  private String statusCode;

  public static final String JSON_PROPERTY_STATUS_TYPE = "statusType";
  @jakarta.annotation.Nullable
  private String statusType;

  public static final String JSON_PROPERTY_STARTED_ON = "startedOn";
  private JsonNullable<OffsetDateTime> startedOn = JsonNullable.<OffsetDateTime>undefined();

  public TestResultCutApiModel() { 
  }

  public TestResultCutApiModel projectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
  }


  public TestResultCutApiModel autoTestExternalId(@jakarta.annotation.Nullable String autoTestExternalId) {
    this.autoTestExternalId = autoTestExternalId;
    return this;
  }

  /**
   * Get autoTestExternalId
   * @return autoTestExternalId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTO_TEST_EXTERNAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAutoTestExternalId() {
    return autoTestExternalId;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTO_TEST_EXTERNAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoTestExternalId(@jakarta.annotation.Nullable String autoTestExternalId) {
    this.autoTestExternalId = autoTestExternalId;
  }


  public TestResultCutApiModel statusCode(@jakarta.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * Get statusCode
   * @return statusCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusCode() {
    return statusCode;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusCode(@jakarta.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
  }


  public TestResultCutApiModel statusType(@jakarta.annotation.Nullable String statusType) {
    this.statusType = statusType;
    return this;
  }

  /**
   * Get statusType
   * @return statusType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusType() {
    return statusType;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusType(@jakarta.annotation.Nullable String statusType) {
    this.statusType = statusType;
  }


  public TestResultCutApiModel startedOn(@jakarta.annotation.Nullable OffsetDateTime startedOn) {
    this.startedOn = JsonNullable.<OffsetDateTime>of(startedOn);
    return this;
  }

  /**
   * Get startedOn
   * @return startedOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getStartedOn() {
        return startedOn.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STARTED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getStartedOn_JsonNullable() {
    return startedOn;
  }
  
  @JsonProperty(JSON_PROPERTY_STARTED_ON)
  public void setStartedOn_JsonNullable(JsonNullable<OffsetDateTime> startedOn) {
    this.startedOn = startedOn;
  }

  public void setStartedOn(@jakarta.annotation.Nullable OffsetDateTime startedOn) {
    this.startedOn = JsonNullable.<OffsetDateTime>of(startedOn);
  }


  /**
   * Return true if this TestResultCutApiModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestResultCutApiModel testResultCutApiModel = (TestResultCutApiModel) o;
    return Objects.equals(this.projectId, testResultCutApiModel.projectId) &&
        Objects.equals(this.autoTestExternalId, testResultCutApiModel.autoTestExternalId) &&
        Objects.equals(this.statusCode, testResultCutApiModel.statusCode) &&
        Objects.equals(this.statusType, testResultCutApiModel.statusType) &&
        equalsNullable(this.startedOn, testResultCutApiModel.startedOn);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, autoTestExternalId, statusCode, statusType, hashCodeNullable(startedOn));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestResultCutApiModel {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    autoTestExternalId: ").append(toIndentedString(autoTestExternalId)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusType: ").append(toIndentedString(statusType)).append("\n");
    sb.append("    startedOn: ").append(toIndentedString(startedOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

