name: Check jreleaser

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-jreleaser:
    uses: ./.github/workflows/jreleaser-common.yml
    with:
      version_source: gradle
      manual_version: ''
      deploy_enabled: false
    secrets:
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}


 