name: Publish to Maven Central

on:
  push:
    tags:
      - '*'  # Triggers on version tags like 2.7.1-TMS-CLOUD

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '2.7.1-TMS-CLOUD'

jobs:
  publish:
    uses: ./.github/workflows/jreleaser-common.yml
    with:
      version_source: ${{ github.event_name == 'push' && 'tag' || 'input' }}
      manual_version: ${{ github.event.inputs.version || '' }}
      deploy_enabled: true
    secrets:
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
    
 